"""
_series — every palette jaan.io offers, and which slot each holds back.

Not a script, and not hand-written: GENERATED by `tools/series_import.py` from jaan.io's
`src/styles/series.css` and `palettes.css`, which are themselves generated by chromaphony.
Baked into this repo rather than read at runtime so a page can be rendered on a machine that has
never seen that repo — the cost is that it goes stale, and the fix is to run the generator, not
to edit this.

Every palette in those files is here, dark and light, and the site's own as `site` (the bare
`:root` in tokens.css). A page this repo draws on its own is drawn for a pale ground, so its
picker offers the `-light` half only; the rest are for a page framed by jaan.io, which takes
whatever palette the host is showing (FRAMED in `_page.py`). Each entry carries its own
background, card and text tokens, so switching palette moves the page's ground along with the
marks — the contrasts in the source are measured against that ground and mean nothing against
another one.

TWO TIERS, upstream's doing and worth knowing here. `--series-1` to `--series-8` are one per hue
family — red, orange, yellow, green, teal, blue, purple, pink — so each has its own name in a
legend; `--series-9` and up are a second shade of one of those. `hues` records where that line
falls. A chart with nine or ten categories is therefore drawing two of them in one family, which
is a thing to know when reading one, not a thing to fix here.

`link` is the slot held back from the categorical set for the connectors, which encode a
relationship rather than a kind of thing. Which slot is a measurement, made per palette against
that palette's own surface colour: of the series, the ones that clear 3:1 against it, and of
those the one sitting furthest from its nearest neighbour among the rest. The comparison is
between the candidate as a LINE — opaque — and the others as SQUARES, at `SQUARE_ALPHA` over the
page's ground, because that is how the two marks are actually painted and the question is
whether a reader could mistake one for the other. `sep` is that distance under the worst of
normal vision and simulated protanopia, deuteranopia and tritanopia (OKLab x100), `con` its
contrast. No topic can wear the link colour, so a line in it is never read as a square.

`topics` is what a chart assigns to categories, in the palette's own order of use, with the link
slot lifted out.
"""

from __future__ import annotations

PALETTES = [
    {"name": "arrietty-2010", "bg": "#1c170f", "card": "#2b251d", "surface": "#342d25", "text": "#eae1d9", "muted": "#aaa198", "link": "#ffd24b", "linkSlot": 7, "sep": 34.8, "con": 9.41, "hues": 8, "topics": ["#6eb447", "#fb86ff", "#006abe", "#b26bfc", "#c23500", "#00d1b8", "#d45e00", "#a82fae", "#9d54e3"]},
    {"name": "arrietty-2010-light", "bg": "#fff9f0", "card": "#f7efe4", "surface": "#f1e8dd", "text": "#39322c", "muted": "#6c635b", "link": "#65006a", "linkSlot": 2, "sep": 30.1, "con": 9.84, "hues": 8, "topics": ["#3c7e00", "#0890ff", "#7323b4", "#8a2300", "#009280", "#af8a00", "#bd5400", "#c34cc8", "#5b0095"]},
    {"name": "earwig-and-the-witch-2020", "bg": "#1e1611", "card": "#2d241e", "surface": "#362c26", "text": "#ece0da", "muted": "#ada19a", "link": "#fec4ff", "linkSlot": 10, "sep": 31.3, "con": 9.42, "hues": 8, "topics": ["#fa813a", "#94b1ff", "#a06fff", "#008a7e", "#ca2200", "#a82fae", "#f7c900", "#00f3a1", "#834dde"]},
    {"name": "earwig-and-the-witch-2020-light", "bg": "#fff9f5", "card": "#faede5", "surface": "#f4e7df", "text": "#3b312d", "muted": "#6e635d", "link": "#65006a", "linkSlot": 6, "sep": 31.9, "con": 9.85, "hues": 8, "topics": ["#b75100", "#1c2ab3", "#9561f3", "#009f91", "#951600", "#ac8b00", "#008a5a", "#7840d1", "#820088"]},
    {"name": "from-up-on-poppy-hill-2011", "bg": "#1c170f", "card": "#2b251d", "surface": "#342d25", "text": "#eae1d9", "muted": "#aaa198", "link": "#a8fa55", "linkSlot": 4, "sep": 39.3, "con": 10.64, "hues": 8, "topics": ["#c9b800", "#39c5ec", "#8443d3", "#008874", "#ff8dbe", "#cf8100", "#e13154", "#ab6fff", "#467600"]},
    {"name": "from-up-on-poppy-hill-2011-light", "bg": "#fff9f0", "card": "#f7efe4", "surface": "#f1e8dd", "text": "#39322c", "muted": "#6c635b", "link": "#2a4a00", "linkSlot": 4, "sep": 28.3, "con": 8.34, "hues": 8, "topics": ["#7b7000", "#007995", "#ab6fff", "#00a089", "#910056", "#c37900", "#fb4c68", "#6d26b8", "#385f00"]},
    {"name": "ghibli-master", "bg": "#1c170f", "card": "#2b251d", "surface": "#342d25", "text": "#eae1d9", "muted": "#aaa198", "link": "#00e8fc", "linkSlot": 6, "sep": 31.2, "con": 9.01, "hues": 8, "topics": ["#ef890f", "#49c2f4", "#a82fae", "#9e6bfe", "#ffcc5f", "#ea3d35", "#008f4e", "#834dde", "#cd56d2"]},
    {"name": "ghibli-master-light", "bg": "#fff9f0", "card": "#f7efe4", "surface": "#f1e8dd", "text": "#39322c", "muted": "#6c635b", "link": "#65006a", "linkSlot": 3, "sep": 32.9, "con": 9.84, "hues": 8, "topics": ["#a65c00", "#00779e", "#9864f7", "#b58700", "#009ba9", "#a80009", "#005a2f", "#6d31c3", "#8b0091"]},
    {"name": "grave-of-the-fireflies-1988", "bg": "#1c170f", "card": "#2b251d", "surface": "#342d25", "text": "#eae1d9", "muted": "#aaa198", "link": "#ffcc5f", "linkSlot": 5, "sep": 31.9, "con": 9.08, "hues": 8, "topics": ["#f18913", "#53c1f9", "#a82fae", "#9b67fa", "#009bab", "#007915", "#de2c51", "#804adb", "#ffa4a9"]},
    {"name": "grave-of-the-fireflies-1988-light", "bg": "#fff9f0", "card": "#f7efe4", "surface": "#f1e8dd", "text": "#39322c", "muted": "#6c635b", "link": "#6d0073", "linkSlot": 3, "sep": 31.2, "con": 9.13, "hues": 8, "topics": ["#a75c00", "#0077a4", "#9864f7", "#b58700", "#009bab", "#00550c", "#a60033", "#672abc", "#fb4c68"]},
    {"name": "howl-s-moving-castle-2004", "bg": "#1c170f", "card": "#2b251d", "surface": "#342d25", "text": "#eae1d9", "muted": "#aaa198", "link": "#82ff84", "linkSlot": 6, "sep": 38.0, "con": 10.71, "hues": 8, "topics": ["#faa300", "#50c1f8", "#a82fae", "#9864f7", "#b08e00", "#009bab", "#da284e", "#ac87ff", "#ff6074"]},
    {"name": "howl-s-moving-castle-2004-light", "bg": "#fff9f0", "card": "#f7efe4", "surface": "#f1e8dd", "text": "#39322c", "muted": "#6c635b", "link": "#6d0073", "linkSlot": 3, "sep": 31.2, "con": 9.13, "hues": 8, "topics": ["#9b6300", "#0077a4", "#9561f3", "#ac8b00", "#00550c", "#009bab", "#a60033", "#672abc", "#fb4c68"]},
    {"name": "kiki-s-delivery-service-1989", "bg": "#15181c", "card": "#23262a", "surface": "#2b2e33", "text": "#e2e2e6", "muted": "#a2a3a8", "link": "#ffd661", "linkSlot": 5, "sep": 35.4, "con": 9.76, "hues": 8, "topics": ["#00bffc", "#ff9b90", "#ab4b00", "#7e46d8", "#0094a4", "#ec468f", "#5dbd05", "#a06fff", "#cf2677"]},
    {"name": "kiki-s-delivery-service-1989-light", "bg": "#f7faff", "card": "#ecf0f6", "surface": "#e6eaf0", "text": "#333337", "muted": "#65656a", "link": "#682b00", "linkSlot": 3, "sep": 31.4, "con": 8.99, "hues": 8, "topics": ["#00779f", "#af534b", "#580ca8", "#af8a00", "#009bab", "#9c0055", "#357200", "#9561f3", "#da3380"]},
    {"name": "laputa-castle-in-the-sky-1986", "bg": "#14181c", "card": "#22262a", "surface": "#2b2f33", "text": "#e2e2e5", "muted": "#a0a3a6", "link": "#ffc334", "linkSlot": 6, "sep": 31.0, "con": 8.42, "hues": 8, "topics": ["#f6842c", "#51c1f8", "#a82fae", "#a46cff", "#d42515", "#0098a5", "#007c57", "#874cdc", "#ff9c8c"]},
    {"name": "laputa-castle-in-the-sky-1986-light", "bg": "#f6fbff", "card": "#ebf1f6", "surface": "#e5eaef", "text": "#343336", "muted": "#636568", "link": "#65006a", "linkSlot": 3, "sep": 30.6, "con": 9.85, "hues": 8, "topics": ["#b05600", "#0077a4", "#985ff1", "#800500", "#b58700", "#009ead", "#006c4b", "#6520b4", "#ac0a00"]},
    {"name": "lupin-iii-the-castle-of-cagliostro-1979", "bg": "#16181c", "card": "#24262b", "surface": "#2c2e33", "text": "#e3e2e6", "muted": "#a3a3a8", "link": "#ffda74", "linkSlot": 7, "sep": 35.4, "con": 10.05, "hues": 8, "topics": ["#00b2fc", "#ffa838", "#007e44", "#a243cb", "#de367e", "#00ddf3", "#ff796b", "#b95ae3", "#cd1819"]},
    {"name": "lupin-iii-the-castle-of-cagliostro-1979-light", "bg": "#f8faff", "card": "#edf0f7", "surface": "#e7e9f0", "text": "#343337", "muted": "#656469", "link": "#5d007c", "linkSlot": 4, "sep": 32.5, "con": 9.86, "hues": 8, "topics": ["#0076aa", "#c77c00", "#00572d", "#c91a6d", "#009bab", "#886b00", "#a30008", "#8018a7", "#df312b"]},
    {"name": "my-neighbor-totoro-1988", "bg": "#121919", "card": "#212727", "surface": "#292f2f", "text": "#e0e3e2", "muted": "#9fa4a3", "link": "#7bff94", "linkSlot": 3, "sep": 36.8, "con": 10.75, "hues": 8, "topics": ["#f49600", "#3971f8", "#d395ff", "#866200", "#b72494", "#00d5b4", "#ff6a67", "#ffb1e5", "#973fca"]},
    {"name": "my-neighbor-totoro-1988-light", "bg": "#f3fcfc", "card": "#eaf2f2", "surface": "#e3ebeb", "text": "#323434", "muted": "#626666", "link": "#710059", "linkSlot": 9, "sep": 28.7, "con": 9.4, "hues": 8, "topics": ["#a06000", "#2154d8", "#004e1b", "#61008c", "#b58700", "#e454bd", "#00927b", "#940018", "#7b1dac"]},
    {"name": "my-neighbors-the-yamadas-1999", "bg": "#1e1613", "card": "#2d2321", "surface": "#362c29", "text": "#ede0dd", "muted": "#ada09d", "link": "#ffd06f", "linkSlot": 3, "sep": 37.3, "con": 9.36, "hues": 8, "topics": ["#f18915", "#67bdff", "#a06fff", "#ca48bd", "#cd1819", "#008472", "#00b967", "#8954e5", "#af2ba3"]},
    {"name": "my-neighbors-the-yamadas-1999-light", "bg": "#fff8f6", "card": "#fbedea", "surface": "#f4e6e2", "text": "#3b312f", "muted": "#6e6260", "link": "#7e0075", "linkSlot": 5, "sep": 27.4, "con": 8.05, "hues": 8, "topics": ["#a75b00", "#1174b2", "#b58700", "#a06fff", "#a30008", "#00a089", "#00572d", "#6222b6", "#9b0c90"]},
    {"name": "nausicaa-of-the-valley-of-the-wind-1984", "bg": "#13181b", "card": "#212729", "surface": "#2a2f32", "text": "#e1e3e4", "muted": "#9fa3a5", "link": "#74ffa2", "linkSlot": 8, "sep": 37.5, "con": 10.68, "hues": 8, "topics": ["#00cefb", "#ff9d73", "#8e3fcc", "#b38800", "#00929a", "#cd1819", "#e15bcd", "#c07cff", "#b1299f"]},
    {"name": "nausicaa-of-the-valley-of-the-wind-1984-light", "bg": "#f5fbff", "card": "#eaf2f4", "surface": "#e4ebef", "text": "#323434", "muted": "#626668", "link": "#76006a", "linkSlot": 7, "sep": 29.0, "con": 8.81, "hues": 8, "topics": ["#007995", "#b0552c", "#731cae", "#b38800", "#009ca5", "#9e0008", "#005427", "#9a4cda", "#950086"]},
    {"name": "ocean-waves-1993", "bg": "#15181c", "card": "#23262b", "surface": "#2c2e33", "text": "#e3e2e6", "muted": "#a2a3a8", "link": "#00ffa2", "linkSlot": 8, "sep": 34.6, "con": 10.24, "hues": 8, "topics": ["#fbb400", "#59c0fc", "#ab4b00", "#8145d6", "#008d9d", "#e3397c", "#ff8386", "#a772ff", "#b68100"]},
    {"name": "ocean-waves-1993-light", "bg": "#f7faff", "card": "#ecf0f7", "surface": "#e7e9f0", "text": "#333336", "muted": "#646469", "link": "#682b00", "linkSlot": 3, "sep": 31.5, "con": 8.95, "hues": 8, "topics": ["#936700", "#0076aa", "#5a09a6", "#009bab", "#c61365", "#fc4d5d", "#00633c", "#a46cff", "#ae7c00"]},
    {"name": "only-yesterday-1991", "bg": "#13181b", "card": "#22262a", "surface": "#2a2f32", "text": "#e1e2e5", "muted": "#a0a3a6", "link": "#71ffa8", "linkSlot": 8, "sep": 34.8, "con": 10.68, "hues": 8, "topics": ["#00b6fb", "#ff9d71", "#7e46d8", "#b98a00", "#008d9d", "#cd1819", "#ffbefc", "#9e6bfe", "#cf54ce"]},
    {"name": "only-yesterday-1991-light", "bg": "#f5fbff", "card": "#ebf1f6", "surface": "#e4ebef", "text": "#333336", "muted": "#636568", "link": "#770078", "linkSlot": 7, "sep": 28.3, "con": 8.48, "hues": 8, "topics": ["#0077a6", "#b05529", "#9b67fa", "#b58700", "#009bab", "#a30008", "#00572d", "#672abc", "#930b94"]},
    {"name": "pom-poko-1994", "bg": "#13191a", "card": "#212728", "surface": "#292f30", "text": "#e1e3e3", "muted": "#9fa4a5", "link": "#ffd98b", "linkSlot": 5, "sep": 33.8, "con": 10.07, "hues": 8, "topics": ["#00b6fc", "#ff9f4f", "#c73600", "#8742d1", "#00e0f7", "#ed458a", "#007a4b", "#a966f7", "#e57c00"]},
    {"name": "pom-poko-1994-light", "bg": "#f3fcfd", "card": "#eaf2f3", "surface": "#e3ebec", "text": "#323434", "muted": "#626667", "link": "#6f1a00", "linkSlot": 3, "sep": 32.3, "con": 9.52, "hues": 8, "topics": ["#0077a7", "#aa5a00", "#6002a2", "#b58700", "#009bab", "#d02572", "#00603a", "#9f5ced", "#7c4100"]},
    {"name": "ponyo-2008", "bg": "#15181c", "card": "#23262a", "surface": "#2b2e33", "text": "#e2e2e6", "muted": "#a2a3a7", "link": "#5fffc1", "linkSlot": 10, "sep": 33.7, "con": 10.74, "hues": 7, "topics": ["#00d3f4", "#b48300", "#8782ff", "#a82fae", "#ffc484", "#ff8577", "#007653", "#6d5ff0", "#bf48c5"]},
    {"name": "ponyo-2008-light", "bg": "#f7faff", "card": "#ecf0f6", "surface": "#e6eaf0", "text": "#333337", "muted": "#656569", "link": "#65006a", "linkSlot": 4, "sep": 31.2, "con": 9.87, "hues": 7, "topics": ["#007a8f", "#b48300", "#482bbc", "#975d00", "#900006", "#00a273", "#786cfe", "#bc45c1", "#006c4b"]},
    {"name": "porco-rosso-1992", "bg": "#121918", "card": "#212726", "surface": "#292f2f", "text": "#e0e3e2", "muted": "#9fa4a3", "link": "#00ffa2", "linkSlot": 8, "sep": 36.5, "con": 10.26, "hues": 8, "topics": ["#00c2fb", "#efa836", "#c23500", "#8443d3", "#b98a00", "#0094a4", "#ed458a", "#a86bfd", "#ff815f"]},
    {"name": "porco-rosso-1992-light", "bg": "#f3fdfb", "card": "#eaf2f1", "surface": "#e3ebeb", "text": "#323434", "muted": "#626666", "link": "#6f1a00", "linkSlot": 3, "sep": 32.6, "con": 9.51, "hues": 8, "topics": ["#00789d", "#996500", "#5d05a4", "#b58700", "#009eaf", "#c91a6d", "#00603a", "#995bec", "#9c2900"]},
    {"name": "princess-mononoke-1997", "bg": "#14181c", "card": "#22262a", "surface": "#2b2f33", "text": "#e2e2e5", "muted": "#a1a3a7", "link": "#e8e300", "linkSlot": 7, "sep": 34.0, "con": 9.9, "hues": 8, "topics": ["#59b758", "#de66e3", "#c23500", "#006cb4", "#bdb7ff", "#00e3c4", "#ffbf86", "#7f61f3", "#ec460e"]},
    {"name": "princess-mononoke-1997-light", "bg": "#f6fbff", "card": "#ebf1f6", "surface": "#e5eaef", "text": "#343336", "muted": "#646569", "link": "#6f1a00", "linkSlot": 3, "sep": 33.8, "con": 9.51, "hues": 8, "topics": ["#1b8020", "#a82fae", "#004575", "#9078ff", "#009983", "#959100", "#794300", "#7453e5", "#cc3800"]},
    {"name": "site", "bg": "#000000", "card": "#1e1e1e", "surface": "#292929", "text": "#e2e2e2", "muted": "#9a9a96", "link": "#fbda00", "linkSlot": 6, "sep": 39.8, "con": 10.48, "hues": 8, "topics": ["#24cb71", "#8a2cb7", "#c91304", "#e870ed", "#008a7e", "#cc7200", "#79ddff", "#af55df", "#007137"]},
    {"name": "the-red-turtle-2016", "bg": "#131919", "card": "#212728", "surface": "#292f30", "text": "#e0e3e3", "muted": "#9fa4a4", "link": "#ffda74", "linkSlot": 5, "sep": 34.2, "con": 10.06, "hues": 8, "topics": ["#fcaa00", "#50c1f8", "#d72824", "#8e3fcc", "#00e4fb", "#dd57c9", "#00ad72", "#be76ff", "#b1299f"]},
    {"name": "the-red-turtle-2016-light", "bg": "#f4fcfc", "card": "#eaf2f3", "surface": "#e3ebec", "text": "#323435", "muted": "#626667", "link": "#6a005f", "linkSlot": 7, "sep": 30.2, "con": 9.76, "hues": 8, "topics": ["#986500", "#0077a4", "#860005", "#6d12a7", "#af8a00", "#009bab", "#006641", "#a053e1", "#8c007e"]},
    {"name": "the-tale-of-the-princess-kaguya-2013", "bg": "#1c170f", "card": "#2b251d", "surface": "#342d25", "text": "#eae1d9", "muted": "#aaa198", "link": "#00fdfc", "linkSlot": 7, "sep": 37.2, "con": 10.63, "hues": 8, "topics": ["#57b759", "#c36dfa", "#006abe", "#ff8ae5", "#c23500", "#dbd000", "#d45e00", "#b3279c", "#79b9ff"]},
    {"name": "the-tale-of-the-princess-kaguya-2013-light", "bg": "#fff9f0", "card": "#f7efe4", "surface": "#f1e8dd", "text": "#39322c", "muted": "#6c635b", "link": "#6b005c", "linkSlot": 4, "sep": 32.5, "con": 9.74, "hues": 8, "topics": ["#168021", "#7e21b0", "#0890ff", "#8a2300", "#989000", "#00908f", "#b95200", "#e056c5", "#004885"]},
    {"name": "the-wind-rises-2013", "bg": "#191810", "card": "#28261d", "surface": "#302e25", "text": "#e7e2d9", "muted": "#a7a399", "link": "#ffc488", "linkSlot": 7, "sep": 33.3, "con": 8.75, "hues": 8, "topics": ["#7eb33a", "#ff82cf", "#bc6bfa", "#006cb4", "#837100", "#009c86", "#e63745", "#71bbff", "#a351de"]},
    {"name": "the-wind-rises-2013-light", "bg": "#fcfbef", "card": "#f3f0e4", "surface": "#eceade", "text": "#37332c", "muted": "#69655c", "link": "#5c008a", "linkSlot": 3, "sep": 29.9, "con": 9.54, "hues": 8, "topics": ["#4f7b00", "#e852b4", "#0091ee", "#a28c00", "#008e7a", "#7a4800", "#770016", "#005b99", "#9441cd"]},
    {"name": "when-marnie-was-there-2014", "bg": "#141914", "card": "#222722", "surface": "#2b2f2a", "text": "#e2e3dd", "muted": "#a1a49e", "link": "#ffda74", "linkSlot": 6, "sep": 36.0, "con": 10.07, "hues": 8, "topics": ["#69b54c", "#ff93f6", "#006abe", "#bc71ff", "#c23500", "#00959e", "#d86100", "#ad2ca7", "#a659e8"]},
    {"name": "when-marnie-was-there-2014-light", "bg": "#f5fcf5", "card": "#ebf2eb", "surface": "#e6ebe5", "text": "#333430", "muted": "#646661", "link": "#680064", "linkSlot": 2, "sep": 29.7, "con": 9.8, "hues": 8, "topics": ["#347f09", "#0890ff", "#7925b5", "#8a2300", "#af8a00", "#008e97", "#bd5400", "#d556ce", "#5d0092"]},
]

BY_NAME = {p["name"]: p for p in PALETTES}
DEFAULT = "ghibli-master-light"

# The opacity a square is painted at, and the alpha `sep` above was measured through. The page
# takes its CSS from here so the number the palettes were chosen against is the number they are
# drawn at — change it in `series_import.py` and regenerate, never here.
SQUARE_ALPHA = 0.5
