#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = []
# ///
"""
_synth_sources — the two files a week is read *against*, invented rather than measured.

Not a script. A session is not only its notes: the letter reads a note against the body and
against the ledger constantly, and `connection_waffle.py` draws a square for each of those two
files precisely because a sentence tying a note to a night's sleep is one of the most legible
connections the page can show. A synthetic vault with no sleep report and no ledger would draw a
connectome with two thirds of the interesting arrows missing.

No model is involved here and none is needed. A sleep report is a table of numbers with a
plausible joint distribution, and a ledger is a list of transactions that adds up — both are
better generated by arithmetic than asked for in prose, because the summary rows have to agree
with the daily rows and a model will not reliably make them. Everything is drawn from a seeded
Random, so a given week is the same week every time it is generated, which is what makes the
committed corpus reviewable as a diff.

The two files are generated BEFORE the notes, not after, and that ordering is the point. Their
figures are handed to the writer as the week's context, so a note about sleep cites the night
the ring actually recorded and a note about money cites what the ledger actually says. That is
what gives the letter something true to connect, rather than two documents about the same week
that happen to sit in one folder.

Payees come from the roster the generator invented for the notes, for the same reason: a cafe
that appears in a note on Tuesday and in the ledger on Tuesday is a connection waiting to be
found, and inventing a second, separate cast would have thrown that away.

No dependencies, so importing this leaves a tool's `dependencies = []` intact.
"""

from __future__ import annotations
import datetime as dt
import random
import re
import statistics

# The window a report covers, and the baseline it is judged against — the same 7-and-21 the real
# generators use, so the summary section reads the same way and the letter reacts to it alike.
WINDOW = 7
BASELINE = 21


# Where a night sits, before anything else is derived from it. Everything in `_night` keys off
# these two numbers rather than off literals, so moving the sleeper moves the whole physiology
# with them — a longer night pulls resting heart rate down and variability up, because that is
# what the correlations below are written in terms of.
#
# The sleeper is a composite, not a person: plausible ranges for a fit adult who sleeps well,
# picked so the report has something for the letter to react to. They were chosen by eye against
# what a ring of this kind reports, so treat them as a believable distribution rather than as
# anyone's measurements — no night here belongs to anybody, and no value was copied from a real
# export. What the generator wants from them is only the shape: correlated metrics, a couple of
# bad nights a week, and a baseline that is not flat.
# Moving these numbers moves the committed corpus with them: the hand-written notes quote the
# figures the generator produced, so a shift here wants `just synth-vault` and a pass over the
# notes that cite nights, or the two stop agreeing.
SLEEP_MEAN = 7.50
SLEEP_SD = 0.70


def _clip(x: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, x))


def _night(rng: random.Random, nudge: float = 0.0) -> dict:
    """One night and the day after it. `nudge` in SDs shifts the night short (negative) or long.

    The metrics are correlated rather than independent, because that is what makes a sleep report
    worth reading: a short night pushes resting heart rate up and heart-rate variability down,
    and a reader who notices one has noticed the others.
    """
    hours = _clip(rng.gauss(SLEEP_MEAN, SLEEP_SD) + nudge * SLEEP_SD, 4.6, 9.6)
    z = (hours - SLEEP_MEAN) / SLEEP_SD
    eff = _clip(rng.gauss(92, 2.4) + z * 0.8, 78, 98)
    latency = _clip(rng.lognormvariate(2.2, 0.5) - z * 2, 3, 42)
    deep = _clip(rng.gauss(21, 4.4) + z * 1.2, 8, 34)
    rem = _clip(rng.gauss(25, 4.2) + z * 1.5, 12, 36)
    light = _clip(100 - deep - rem, 34, 70)
    midsleep = _clip(rng.gauss(2.4, 0.75) - z * 0.35, 0.4, 5.2)  # hours after midnight
    score = int(_clip(56 + 4.4 * hours + 0.35 * (eff - 90) - 0.25 * latency, 40, 97))

    rhr = _clip(rng.gauss(47.5, 2.8) - z * 1.6, 38, 62)
    hrv = _clip(rng.gauss(82, 15) + z * 9, 30, 150)
    return {
        "hours": hours, "eff": eff, "latency": latency, "deep": deep, "rem": rem,
        "light": light, "midsleep": midsleep, "score": score,
        "rhr": rhr, "avg_hr": rhr + _clip(rng.gauss(4.2, 1.0), 1.5, 8),
        "hrv": hrv, "breath": _clip(rng.gauss(13.8, 0.45), 12.4, 15.6),
        "temp": rng.gauss(0.02, 0.24),
        "act_score": int(_clip(rng.gauss(87, 7), 55, 99)),
        "met": _clip(rng.gauss(500, 190), 20, 1150),
        "cv": _clip(rng.gauss(0.66, 0.13), 0.18, 1.05),
    }


def _hhmm(hours_after_midnight: float) -> str:
    total = int(round(hours_after_midnight * 60)) % (24 * 60)
    return f"{total // 60:02d}:{total % 60:02d}"


def _signed(x: float, places: int = 2) -> str:
    return f"{x:+.{places}f}"


# (label, unit, key, how to read the value out of a night)
METRICS = (
    ("Total sleep", "h", lambda n: n["hours"]),
    ("Sleep efficiency", "%", lambda n: n["eff"]),
    ("Sleep latency", "min", lambda n: n["latency"]),
    ("Deep sleep", "%", lambda n: n["deep"]),
    ("REM sleep", "%", lambda n: n["rem"]),
    ("Light sleep", "%", lambda n: n["light"]),
    ("Midsleep time", "h", lambda n: n["midsleep"] + 12),
    ("Resting HR", "bpm", lambda n: n["rhr"]),
    ("HRV (RMSSD)", "ms", lambda n: n["hrv"]),
    ("Respiratory rate", "/min", lambda n: n["breath"]),
    ("Temperature deviation", "°C", lambda n: n["temp"]),
    ("Within-day activity CV", "—", lambda n: n["cv"]),
    ("Active MET minutes", "min", lambda n: n["met"]),
)


def oura(date: str, seed: int, key: str = "") -> dict:
    """A week of nights and the three weeks behind it, as numbers. Rendering is separate.

    Returned rather than printed so the notes can be written against the same figures the
    report shows: `digest` below is what the writer is told, and it is read off this.
    """
    # `key` is what the numbers are drawn from and `date` is only what they are labelled with.
    # They differ when a hand-written corpus is shifted onto a live calendar: the notes quote
    # these figures to two decimal places, so the figures must not move when the dates do.
    rng = random.Random(f"oura-{key or date}-{seed}")
    end = dt.date.fromisoformat(date)
    # One or two nights a week go short. A flat week gives a reader nothing to notice and gives
    # the letter nothing to say, and a real week is not flat.
    rough = rng.sample(range(WINDOW), rng.choice([1, 1, 2]))
    # The three weeks behind the window get short nights at the same rate. Without them the
    # baseline was a sleeper who never had a bad night, so every real week read as a decline
    # against a reference that had never happened.
    rough_base = set(rng.sample(range(BASELINE), 4))
    days, base = [], []
    for i in range(BASELINE, 0, -1):
        day = end - dt.timedelta(days=WINDOW - 1 + i)
        nudge = rng.uniform(-1.35, -0.75) if i in rough_base else rng.uniform(-0.25, 0.35)
        base.append({"date": day.isoformat(), **_night(rng, nudge)})
    for i in range(WINDOW):
        day = end - dt.timedelta(days=WINDOW - 1 - i)
        nudge = rng.uniform(-1.35, -0.75) if i in rough else rng.uniform(-0.25, 0.35)
        days.append({"date": day.isoformat(), **_night(rng, nudge)})
    return {"date": date, "days": days, "baseline": base}


# No `\b` in front: the ledger's header is italic, `_2026-11-05 to …`, and an underscore is a
# word character, so a word boundary there never matched and that one year was printed.
YEAR = re.compile(r"(?<!\d)20\d\d-(\d{2}-\d{2})\b")
SLASHED = re.compile(r"\b(\d{1,2}/\d{1,2})/20\d\d\b")


def undated(text: str) -> str:
    """Every date in a generated report, without its year.

    These two files are units on the connectome — the chart draws a square for each and shows
    its contents — so a year printed here is a year a reader sees, and the whole point of the
    synthetic corpus dropping them is that it does not start looking stale. The notes beside
    them are written the same way; see `synth_vault.shifter`.
    """
    return SLASHED.sub(r"\1", YEAR.sub(r"\1", text))


def oura_md(data: dict) -> str:
    """The week's nights as the markdown the review reads — same sections, same columns."""
    days, base = data["days"], data["baseline"]
    end = dt.date.fromisoformat(data["date"])

    sleep_rows = "\n".join(
        f"| {d['date']} | {d['hours']:.2f} | {d['eff']:.0f} | {d['latency']:.0f} | "
        f"{d['deep']:.0f} | {d['rem']:.0f} | {d['light']:.0f} | {_hhmm(d['midsleep'])} | "
        f"{d['score']} |" for d in days)
    phys_rows = "\n".join(
        f"| {d['date']}{' \\*' if i == len(days) - 1 else ''} | {d['rhr']:.0f} | "
        f"{d['avg_hr']:.0f} | {d['hrv']:.0f} | {d['breath']:.1f} | {d['temp']:.2f} | "
        f"{d['act_score']} | {d['met']:.0f} | {d['cv']:.2f} |"
        for i, d in enumerate(days))

    cmp_rows = []
    for label, unit, read in METRICS:
        wk = [read(d) for d in days]
        bl = [read(d) for d in base]
        wm, bm = statistics.fmean(wk), statistics.fmean(bl)
        wsd, bsd = statistics.pstdev(wk), statistics.pstdev(bl)
        z = (wm - bm) / bsd if bsd else 0.0
        cmp_rows.append(f"| {label} | {unit} | {wm:.2f} | {wsd:.2f} | {bm:.2f} | {bsd:.2f} | "
                        f"{_signed(wm - bm)} | {_signed(z)} |")

    # Single days that ran more than 1.5 baseline SDs from the baseline mean. The section a
    # reader actually looks at, and the one a letter tends to quote.
    flags = []
    for label, _unit, read in METRICS:
        bl = [read(d) for d in base]
        bm, bsd = statistics.fmean(bl), statistics.pstdev(bl)
        if bsd < 1e-9:
            continue
        for d in days:
            z = (read(d) - bm) / bsd
            if abs(z) >= 1.5:
                flags.append((abs(z), f"| {d['date']} | {label} | {read(d):.2f} | {bm:.2f} | "
                                      f"{_signed(z)} | {'above' if z > 0 else 'below'} |"))
    flag_rows = "\n".join(row for _, row in sorted(flags, reverse=True)[:12]) or \
        "| — | — | — | — | — | — |"

    roll = [statistics.pstdev([n["hours"] for n in (base + days)[i:i + WINDOW]])
            for i in range(len(base) + len(days) - WINDOW + 1)]
    roll_rows = "\n".join(
        f"| {(end - dt.timedelta(days=len(roll) - 1 - i)).isoformat()} | {v:.2f} |"
        for i, v in enumerate(roll[-WINDOW:]))
    base_start, base_end = base[0]["date"], base[-1]["date"]

    return undated(f"""# Oura metrics — last 7 days

_generated {end.month}/{end.day}/{end.year}, 10:15:16 AM · 7 days, against the previous 3 weeks (21 days with data, {base_start} … {base_end})_

## Sleep

_Stage percentages are of total sleep time, not time in bed._

| Date | Sleep h | Eff % | Latency min | Deep % | REM % | Light % | Midsleep | Score |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
{sleep_rows}

## Physiology and activity

_HR and HRV are nocturnal. Activity CV is the coefficient of variation of the day's 1-minute MET series (full 24 h, sleep included) — a within-day variability scalar._

| Date | Resting HR | Avg HR | HRV ms | Breath | Temp Δ°C | Act score | Active MET min | Act CV |
|---|---:|---:|---:|---:|---:|---:|---:|---:|
{phys_rows}

\\* Today — activity is still accumulating, so its activity columns are shown but excluded from the baselines below. The sleep row for the same date is complete.

## Last 7 days vs the previous 3 weeks

_Baseline is the previous 3 weeks — the days before this window, so nothing in the window helped set the mean it is judged against. Δ is the change in the metric's own unit; z is that change in baseline SDs, which is what makes metrics comparable to each other._

| Metric | Unit | Week mean | Week SD | Baseline mean | Baseline SD | Δ | z |
|---|---|---:|---:|---:|---:|---:|---:|
{chr(10).join(cmp_rows)}

## Sleep-duration variability (7-night rolling SD)

_Night-to-night spread in how long sleep ran, rather than how long it ran on average. A week can hold its mean and still scatter, and the scatter is the part that is felt._

| Date | Rolling SD h |
|---|---:|
{roll_rows}

_The same rolling SD averaged {statistics.fmean(roll[:BASELINE - WINDOW + 1]):.2f} h across the previous 3 weeks._

## Deviations beyond ±1.5 SD of baseline

_Single days in this window, each against the mean and SD of the previous 3 weeks._

| Date | Metric | Value | Baseline mean | z | Direction |
|---|---|---:|---:|---:|---|
{flag_rows}

## How to read this

- Everything here is measured against **the previous 3 weeks**, not against any stable reference. That is a real comparison period rather than the window judging itself, but it inherits whatever those weeks were.
- A z of ±1 is one baseline day's worth of spread, so a *weekly mean* moving that far is a large shift — seven nights average most of the noise out. Read ±0.5 as visible and ±1 as pronounced.
- Several signals moving together mean more than any one of them. Shorter sleep, a higher resting heart rate and a wider spread in bedtime say something in combination that none says alone.
- Change from your own baseline matters; population norms mostly do not.
- Stage percentages from a ring are trend indicators, not measurements.
- This is a self-tracking summary and nothing more.
""")


def digest_oura(data: dict) -> str:
    """The week's physiology in three sentences, for the writer of the notes to work from."""
    days = data["days"]
    hours = [d["hours"] for d in days]
    worst = min(days, key=lambda d: d["hours"])
    best = max(days, key=lambda d: d["hours"])
    base_rhr = statistics.fmean([d["rhr"] for d in data["baseline"]])
    rhr = statistics.fmean([d["rhr"] for d in days])
    return undated(
        f"Slept {statistics.fmean(hours):.1f} h a night on average, spread {statistics.pstdev(hours):.1f} h. "
        f"Worst night {worst['date']} at {worst['hours']:.1f} h (score {worst['score']}); "
        f"best {best['date']} at {best['hours']:.1f} h (score {best['score']}). "
        f"Resting heart rate averaged {rhr:.0f}, against {base_rhr:.0f} over the previous three weeks."
    )


# What a month of ordinary spending is made of. Weights are how often a category comes up in a
# week, not how much it costs — rent is one line and half the money.
CATEGORIES = (
    ("Expenses:Food:Coffee", 5.0, 4.0, 9.5),
    ("Expenses:Food:Groceries", 2.0, 14.0, 96.0),
    ("Expenses:Food:Restaurants", 3.0, 11.0, 58.0),
    ("Expenses:Transport:Transit", 2.0, 2.9, 34.0),
    ("Expenses:Transport:Bikeshare", 1.4, 4.5, 24.0),
    ("Expenses:Shopping:Online", 2.4, 9.0, 140.0),
    ("Expenses:Entertainment:Events", 1.2, 12.0, 95.0),
    ("Expenses:Services:Software", 1.0, 3.0, 22.0),
    ("Expenses:Misc:PersonToPerson", 0.9, 10.0, 60.0),
    ("Expenses:Home:Internet", 0.34, 49.99, 49.99),
    ("Expenses:Health:Pharmacy", 0.6, 7.0, 38.0),
)

CARD = "Liabilities:DK:Local:CreditCard"
CHECKING = "Assets:DK:Retail:Checking"


def finances(date: str, seed: int, payees: list[str], key: str = "") -> dict:
    """A week of transactions, drawn from the roster's own shops and clubs."""
    rng = random.Random(f"money-{key or date}-{seed}")  # see oura(): values keyed, dates labelled
    end = dt.date.fromisoformat(date)
    start = end - dt.timedelta(days=WINDOW + 1)
    pool = payees or ["Corner Market", "The Kettle", "Transit Authority"]
    # A shop sells one kind of thing. Each category keeps its own two or three merchants, drawn
    # from the same roster the notes use and drawn the same way every run, so a cafe that turns
    # up in a note on Tuesday is the cafe on Tuesday's ledger line rather than a coincidence.
    merchants = {
        account: random.Random(f"{account}-{seed}").sample(pool, min(3, len(pool)))
        for account, _, _, _ in CATEGORIES
    }

    entries = []
    # Rent lands once a month and dominates the week it lands in — which is why the ledger is
    # worth reading beside the notes at all: one week is nothing and the next is a wall.
    if end.day <= 8:
        entries.append({"date": (start + dt.timedelta(days=rng.randint(0, 2))).isoformat(),
                        "payee": "Landlord", "account": "Expenses:Home:Rent",
                        "amount": round(rng.uniform(2180, 2340), 2), "asset": CHECKING})
    for account, weight, lo, hi in CATEGORIES:
        for _ in range(_poisson(rng, weight)):
            entries.append({
                "date": (start + dt.timedelta(days=rng.randint(0, WINDOW))).isoformat(),
                "payee": rng.choice(merchants[account]), "account": account,
                "amount": round(rng.uniform(lo, hi), 2),
                "asset": CARD if account != "Expenses:Home:Rent" else CHECKING,
            })
    if rng.random() < 0.5:
        entries.append({"date": (start + dt.timedelta(days=rng.randint(0, WINDOW))).isoformat(),
                        "payee": "Interest", "account": "Income:Interest",
                        "amount": -round(rng.uniform(4, 180), 2), "asset": CHECKING})
    entries.sort(key=lambda e: (e["date"], e["payee"]))
    return {"date": date, "start": start.isoformat(), "entries": entries}


def _poisson(rng: random.Random, mean: float) -> int:
    """Knuth's method. `random.Random` has no Poisson, and a fixed count per category is not one."""
    import math
    limit, k, p = math.exp(-mean), 0, 1.0
    while True:
        p *= rng.random()
        if p <= limit:
            return k
        k += 1


def finances_md(data: dict) -> str:
    """The ledger as the markdown the review reads: a category summary, then the entries."""
    entries = data["entries"]
    totals: dict[str, float] = {}
    for e in entries:
        totals[e["account"]] = totals.get(e["account"], 0.0) + e["amount"]
    ordered = sorted(totals.items(), key=lambda kv: -abs(kv[1]))
    spent = sum(v for v in totals.values() if v > 0)
    earned = -sum(v for v in totals.values() if v < 0)

    summary = "\n".join(f"{name:<48}{amount:>10,.2f}" for name, amount in ordered)
    body = "\n\n".join(
        f'{e["date"]} * "{e["payee"]}" ""\n'
        f'  {e["asset"]:<44}{-e["amount"]:>8.2f} USD\n'
        f'  {e["account"]:<44}{e["amount"]:>8.2f} USD'
        for e in entries)

    return undated(f"""# Finances — last 7 days

_{data['start']} to {data['date']} · {len(entries)} transactions · categorized double-entry, straight from the ledger_

## Where it went

```text
{summary}

{'spent':<48}{spent:>10,.2f}
{'earned':<48}{earned:>10,.2f}
```

## Entries

```beancount
{body}
```
""")


def digest_finances(data: dict) -> str:
    """The week's money in one sentence, for the writer of the notes to work from."""
    entries = data["entries"]
    totals: dict[str, float] = {}
    for e in entries:
        totals[e["account"]] = totals.get(e["account"], 0.0) + e["amount"]
    spent = sum(v for v in totals.values() if v > 0)
    top = sorted(((v, k) for k, v in totals.items() if v > 0), reverse=True)[:3]
    where = ", ".join(f"{k.split(':')[-1].lower()} {v:,.0f}" for v, k in top)
    payees = sorted({e["payee"] for e in entries if e["amount"] > 0})
    return (f"Spent {spent:,.0f} dollars across {len(entries)} transactions — mostly {where}. "
            f"Places that took money this week: {', '.join(payees[:10])}.")
