#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"   # math.cbrt
# dependencies = []
# ///
"""
series_import — regenerate `_series.py` from jaan.io's series.css and palettes.css.

`_series.py` says it is generated and not to be edited, and until now there was nothing in this
repo that generated it. That is a comment asking to be disbelieved. This is the generator.

WHAT IT READS. `series.css` for the categorical set of every `-light` palette, and
`palettes.css` for that palette's ground — bg, card, surface, text, muted. Both are themselves
generated by chromaphony from the site's tokens, so this is a third-hand copy, which is the
whole reason it is worth being able to re-make on demand rather than by hand.

WHAT IT COMPUTES, and the only thing here that is not a copy: which slot is held back for the
connectors. A line and a square on the connectome mean different things, so the colour a line is
drawn in must never be one a square could wear. The rule is the one `_series.py` has always
documented — of the series, the ones that clear 3:1 against the surface they are drawn on, and
of those the one sitting furthest from its nearest neighbour among the rest. Distance is OKLab,
taken as the worst of normal vision and simulated protanopia, deuteranopia and tritanopia.

THE MATHS IS PORTED, NOT INVENTED. Every constant below comes from
`jaan.io/scripts/contrast-check.mjs`, which is what measured the figures written into the CSS
comments in the first place. `--check` reproduces those figures from this port and diffs them
against what the file says, so a port that has drifted says so instead of quietly grading its
own work. Run it before trusting a regeneration.

Usage:
    ./series_import.py --check          # verify the port against the CSS's own numbers
    ./series_import.py                  # rewrite tools/_series.py
    ./series_import.py --site ~/dev/jaan.io
"""

from __future__ import annotations
import argparse
import math
import re
import sys
from pathlib import Path

from _env import REPO_ROOT

SITE = Path("~/projects/jaan.io").expanduser()
OUT = REPO_ROOT / "tools" / "_series.py"

# A mark has to clear this against the ground it sits on to be a mark at all (WCAG 1.4.11).
MARK_CONTRAST = 3.0

# What the connectome paints a square at. It matters here because the separation between the
# connectors and the categories is the whole reason a slot is held back, and measuring that on
# the raw hex measures a colour the page never shows: at half opacity over a pale ground every
# square moves a long way toward the paper, and the distance from an opaque line changes with
# it. Emitted into `_series.py` so the renderer takes its CSS from the same number this was
# measured at, rather than the two agreeing by memory.
SQUARE_ALPHA = 0.5

# Machado, Oliveira & Fernandes (2009), full severity. Verbatim from contrast-check.mjs.
CVD = {
    "protan": ((0.152286, 1.052583, -0.204868),
               (0.114503, 0.786281, 0.099216),
               (-0.003882, -0.048116, 1.051998)),
    "deutan": ((0.367322, 0.860646, -0.227968),
               (0.280085, 0.672501, 0.047413),
               (-0.01182, 0.04294, 0.968881)),
    "tritan": ((1.255528, -0.076749, -0.178779),
               (-0.078411, 0.930809, 0.147602),
               (0.004733, 0.691367, 0.3039)),
}
VISIONS = ("normal", *CVD)


def rgb(hex_: str) -> tuple[int, int, int]:
    h = hex_.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def channel(c: float) -> float:
    s = c / 255
    return s / 12.92 if s <= 0.03928 else ((s + 0.055) / 1.055) ** 2.4


def luminance(c) -> float:
    r, g, b = (channel(x) for x in c)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def ratio(a, b) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def oklab(linear) -> tuple[float, float, float]:
    """Linear RGB → OKLab (Björn Ottosson's matrices)."""
    r, g, b = linear
    l = math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b)
    m = math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b)
    s = math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b)
    return (0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s,
            1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s,
            0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s)


def seen(c) -> list[tuple[float, float, float]]:
    """One colour as four colours: how it looks to normal vision and to each deficiency."""
    linear = [channel(x) for x in c]
    out = [oklab(linear)]
    for m in CVD.values():
        out.append(oklab([min(1.0, max(0.0, sum(row[i] * linear[i] for i in range(3))))
                          for row in m]))
    return out


def apart(a, b) -> float:
    """How far apart two colours look, taken as the worst of the four visions."""
    return min(math.dist(x, y) for x, y in zip(seen(a), seen(b)))


def painted(colour: str, ground: str, alpha: float = SQUARE_ALPHA):
    """A square as the page actually paints it: the series colour, at alpha, over the ground."""
    c, g = rgb(colour), rgb(ground)
    return tuple(round(alpha * c[i] + (1 - alpha) * g[i]) for i in range(3))


def blocks(css: str) -> dict[str, str]:
    """Every `:root[data-palette="…"]` block in a file, by palette name."""
    return {m[1]: m[2] for m in re.finditer(
        r':root\[data-palette="([^"]+)"\]\s*\{(.*?)\n\}', css, re.S)}


def tokens(block: str) -> dict[str, str]:
    """`--name: #hex` pairs, a three-digit hex written out to six (tokens.css says `#000`)."""
    return {k: v if len(v) == 7 else "#" + "".join(ch * 2 for ch in v[1:])
            for k, v in re.findall(r"--([a-z-]+):\s*(#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b)", block)}


def series_of(block: str) -> list[str]:
    """The categorical set, in the order of use the generator wrote it in."""
    found = re.findall(r"--series-(\d+):\s*(#[0-9a-fA-F]{6})", block)
    return [hexv for _, hexv in sorted(found, key=lambda kv: int(kv[0]))]


def stated(block: str) -> list[float]:
    """The contrast figures the CSS states beside each series, for `--check` to disagree with."""
    return [float(m) for m in re.findall(r"--series-\d+:\s*#[0-9a-fA-F]{6};\s*/\*\s*([\d.]+):1", block)]


def link_slot(colours: list[str], surface: str, bg: str) -> tuple[int, float, float]:
    """Which slot the connectors take: (1-based slot, separation, contrast).

    Eligible on contrast against the surface, chosen on distance. The distance is between the
    candidate as a LINE — opaque, full strength — and every other slot as a SQUARE, which is to
    say at `SQUARE_ALPHA` over the page's ground. That asymmetry is the point: the two marks are
    painted differently and the question being asked is whether a reader could mistake one for
    the other, not whether two hex values are far apart in the abstract.

    The separation reported is the winner's nearest neighbour under the worst of the four
    visions — a floor on how unlike any square that line can look, not an average anybody could
    hide behind.
    """
    ink = rgb(surface)
    eligible = [i for i, c in enumerate(colours) if ratio(rgb(c), ink) >= MARK_CONTRAST]
    if not eligible:                                   # nothing clears the ground: take the best
        eligible = [max(range(len(colours)), key=lambda i: ratio(rgb(colours[i]), ink))]
    best, sep = None, -1.0
    for i in eligible:
        near = min(apart(rgb(colours[i]), painted(c, bg))
                   for j, c in enumerate(colours) if j != i)
        if near > sep:
            best, sep = i, near
    return best + 1, round(sep * 100, 1), round(ratio(rgb(colours[best]), ink), 2)


HEAD = '''"""
_series — every palette jaan.io offers, and which slot each holds back.

Not a script, and not hand-written: GENERATED by `tools/series_import.py` from jaan.io's
`src/styles/series.css` and `palettes.css`, which are themselves generated by chromaphony.
Baked into this repo rather than read at runtime so a page can be rendered on a machine that has
never seen that repo — the cost is that it goes stale, and the fix is to run the generator, not
to edit this.

Every palette in those files is here, dark and light, and the site's own as `site` (the bare
`:root` in tokens.css). A page this repo draws on its own is drawn for a pale ground, so its
picker offers the `-light` half only; the rest are for a page framed by jaan.io, which takes
whatever palette the host is showing (FRAMED in `_page.py`). Each entry carries its own
background, card and text tokens, so switching palette moves the page's ground along with the
marks — the contrasts in the source are measured against that ground and mean nothing against
another one.

TWO TIERS, upstream's doing and worth knowing here. `--series-1` to `--series-8` are one per hue
family — red, orange, yellow, green, teal, blue, purple, pink — so each has its own name in a
legend; `--series-9` and up are a second shade of one of those. `hues` records where that line
falls. A chart with nine or ten categories is therefore drawing two of them in one family, which
is a thing to know when reading one, not a thing to fix here.

`link` is the slot held back from the categorical set for the connectors, which encode a
relationship rather than a kind of thing. Which slot is a measurement, made per palette against
that palette's own surface colour: of the series, the ones that clear 3:1 against it, and of
those the one sitting furthest from its nearest neighbour among the rest. The comparison is
between the candidate as a LINE — opaque — and the others as SQUARES, at `SQUARE_ALPHA` over the
page's ground, because that is how the two marks are actually painted and the question is
whether a reader could mistake one for the other. `sep` is that distance under the worst of
normal vision and simulated protanopia, deuteranopia and tritanopia (OKLab x100), `con` its
contrast. No topic can wear the link colour, so a line in it is never read as a square.

`topics` is what a chart assigns to categories, in the palette's own order of use, with the link
slot lifted out.
"""

from __future__ import annotations

PALETTES = [
'''

TAIL = ''']

BY_NAME = {p["name"]: p for p in PALETTES}
DEFAULT = "ghibli-master-light"

# The opacity a square is painted at, and the alpha `sep` above was measured through. The page
# takes its CSS from here so the number the palettes were chosen against is the number they are
# drawn at — change it in `series_import.py` and regenerate, never here.
SQUARE_ALPHA = %s
'''


def main() -> None:
    ap = argparse.ArgumentParser(description="Regenerate tools/_series.py from jaan.io's CSS.")
    ap.add_argument("--site", type=Path, default=SITE, help=f"jaan.io checkout (default {SITE}).")
    ap.add_argument("--out", type=Path, default=OUT, help="Where _series.py goes.")
    ap.add_argument("--check", action="store_true",
                    help="Reproduce the contrast figures the CSS states and diff against them. "
                         "Writes nothing. The port is only trustworthy while this passes.")
    args = ap.parse_args()

    styles = args.site / "src" / "styles"
    for name in ("series.css", "palettes.css"):
        if not (styles / name).is_file():
            sys.exit(f"No {name} under {styles} — point --site at a jaan.io checkout.")
    series_css = blocks((styles / "series.css").read_text())
    palette_css = blocks((styles / "palettes.css").read_text())

    # The site's own palette — the one on screen before anybody presses the switcher — is the bare
    # `:root` in tokens.css, series and ground together, and has no name there. It is "site" here,
    # which is what a framed page takes when the host's <html> carries no data-palette.
    own = re.search(r"^:root\s*\{(.*?)\n\}", (styles / "tokens.css").read_text(), re.S | re.M)
    if own:
        series_css["site"] = palette_css["site"] = own[1]

    names = sorted(series_css)
    print(f"read     {len(names)} palettes from {styles}")

    # ── the port, checked against the numbers the source already published ────────────────
    worst, checked = 0.0, 0
    for name in names:
        ground = rgb(tokens(palette_css[name])["bg"])
        for colour, says in zip(series_of(series_css[name]), stated(series_css[name])):
            worst = max(worst, abs(ratio(rgb(colour), ground) - says))
            checked += 1
    print(f"check    {checked} stated contrasts reproduced, worst disagreement {worst:.3f}")
    if worst > 0.005:
        sys.exit("The port disagrees with the CSS it is reading. Fix the maths before writing.")
    if args.check:
        print("\nCheck only — nothing written.")
        return

    rows = []
    for name in names:
        ground = tokens(palette_css[name])
        colours = series_of(series_css[name])
        slot, sep, con = link_slot(colours, ground["surface"], ground["bg"])
        hues = re.search(r"--series-hues:\s*(\d+)", series_css[name])
        topics = [c for i, c in enumerate(colours, 1) if i != slot]
        rows.append(
            '    {"name": "%s", "bg": "%s", "card": "%s", "surface": "%s", "text": "%s", '
            '"muted": "%s", "link": "%s", "linkSlot": %d, "sep": %s, "con": %s, "hues": %s, '
            '"topics": %s},' % (
                name, ground["bg"], ground["card"], ground["surface"], ground["text"],
                ground["text-muted"], colours[slot - 1], slot, sep, con,
                hues.group(1) if hues else "None",
                "[" + ", ".join(f'"{c}"' for c in topics) + "]"))
        print(f"  {name:<46} link slot {slot:>2} · sep {sep:>5} · {con:>5}:1 · {len(topics)} topics")

    args.out.write_text(HEAD + "\n".join(rows) + "\n" + TAIL % SQUARE_ALPHA)
    print(f"\n  wrote  {args.out}")


if __name__ == "__main__":
    main()
