#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["baml-bridge==0.17.0", "pydantic>=2"]
# ///
"""
synth_corpus — four weeks of somebody who does not exist, in the formats the pipeline reads.

The connectome pages are the best thing in this repo and they cannot be shown to anybody,
because every square on them is a diff of a private note. This writes a second vault so they
can be: `synthetic/sessions/<date>/` with a `microlite.md`, a sleep report, a ledger and an
`edit-me.md`, byte-compatible with what the real providers write. Point the rest of the repo at
it with `PETROGRAPH_OUT=synthetic` and every tool here — the waffle, `just connections`,
`just topics`, the connectome and its topic colouring — runs unchanged on data with nobody in
it. Nothing downstream was modified to make that work, and nothing downstream can tell.

WHAT REACHES THE MODEL THAT WRITES IT. `synthetic/profile.json`, which is sixty numbers;
`synthetic/style-guide.md`, which is those numbers written as instructions; and a list of
subjects, from `_story.py` under `--story` and from `_synth.SUBJECTS` otherwise. That is all. No
note, no title, no name, no sentence from the real vault is in this tool's inputs, and
`synth_profile.py`'s return type is what guarantees it
— see `baml_src/synth_profile.baml`. Every name in the output was invented by the first call
this tool makes and reused by all the rest.

FIVE STAGES, and the order is load-bearing.

  1. The roster. One call, and every later call chooses from it. A journal names the same dozen
     people for months, and recurrence is most of what separates a vault from four hundred
     unrelated paragraphs.
  2. The sources. The sleep report and the ledger, generated by arithmetic in `_synth_sources`,
     BEFORE a word of prose exists. Their figures are then handed to the writer, so a note about
     a bad night cites the night the ring recorded and a note about money cites the ledger's own
     number. That is what gives the letter something true to tie together — and a hunk-to-source
     arrow is a third of what the connectome draws.
  3. The threads. One call per subject, each planning a few notes and what happens in each
     of them week by week. A thread with a beat in week 1 and a beat in week 4 is a note the
     writer came back to, which is the inter-week arrow the page exists to show; asking for it
     up front is the only way to be sure there is one to find.
  4. The edits. One beat becomes one or two splices into the note's accumulated text. The tool
     picks where the change lands — appended, prepended, a rewritten passage, a deleted one —
     because that choice is what produces the profile's mix of added, mixed and removed hunks,
     and a model asked to choose would append every time.
  5. The diffs, by `difflib`. A model is never asked for a diff. It writes prose; this splices
     it in and diffs the before against the after. That matters more than it sounds: every id on
     the connectome is a position in one of these files, so the line counts in an `@@` header
     have to be arithmetic rather than something that looks like arithmetic.

There is no content filter on any of this and there deliberately is not one any more. What kept
the real vault out was never a word list — it is `synth_profile.py`'s return type, which has no
string field in it — and the word list that used to sit here only stopped the synthetic writer
from saying how they felt. A journal whose author may not be upset is a thinner test of the
connectome, not a safer one. See `_synth.py`.

The whole generation is cached call by call under `share/.baml-cache`, keyed by the prompts, the
profile, the style guide and the dates. Re-running to change how the files are laid out costs
nothing; changing a prompt correctly misses.

Usage:
    ./synth_corpus.py                     # write synthetic/sessions/ (uses the cache if warm)
    ./synth_corpus.py --dry-run           # the call count and what it would cost
    ./synth_corpus.py --weeks 2 --end 2026-02-13
    ./synth_corpus.py --no-cache          # generate a different vault from the same inputs
"""

from __future__ import annotations
import argparse
import datetime as dt
import difflib
import json
import os
import random
import re
import shutil
import sys
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from _cache import cache_path, write_atomic
from _env import REPO_ROOT, api_key
from _session import LIFELOG, ensure_stub
from _synth import (ANCHOR, PROFILE, SESSIONS, STYLE_GUIDE, SUBJECTS, SYNTH_ROOT, WEEKS,
                    label, week_dates)
from _synth_sources import (digest_finances, digest_oura, finances, finances_md, oura, oura_md)
from _term import link

CACHE_DIR = REPO_ROOT / "share" / ".baml-cache"
PROMPT = REPO_ROOT / "baml_src" / "synth_write.baml"

# The four half-sentences `prompts/act-analysis.md` leaves for a person to finish by hand. The
# synthetic week answers them in its `## Week context`, which is the same place a real week's
# answers go — so the bundle carries the blanks and, a few lines later, the filled-in version of
# themselves, exactly as it does when somebody pastes the prompt into a chat window.
#
# Matched at the head of a paragraph and in order, without the ellipsis, because the ellipsis is
# the blank rather than punctuation the answer should keep: what comes back is "This upcoming
# week I need to find out who was on that roof", which is the opener filled in and reads like a
# person wrote it. `Emotionally I` is accepted alongside `Emotionally, I` for the same reason,
# and the match is case-insensitive because the style guide asks for mostly lower case and gets
# it — "this upcoming week i need to" is the voice working, not the format failing.
# Checked at all because a draft that quietly drops one leaves the read a question nobody asked.
OPENERS = (r"This upcoming week\b", r"Tomorrow\b", r"Today\b", r"Emotionally,? I\b")


def has_openers(text: str) -> bool:
    """Whether all four openers start a paragraph, in the order the prompt asks for."""
    found = 0
    for para in (p.strip() for p in re.split(r"\n\s*\n", text or "")):
        if found < len(OPENERS) and para and re.match(OPENERS[found], para, re.I):
            found += 1
    return found == len(OPENERS)

# How many notes each allowed topic is asked for. Sixteen topics at four notes apiece is
# sixty-four notes, which with the beat distribution below lands near the profile's forty-five
# notes and fifty-eight edits a week.
NOTES_PER_TOPIC = 4

# How many notes one act of a story leaves behind, when `--story` is on. Sized to land near the
# profile's forty-five notes a week; roughly half of each act's are files carried forward from an
# earlier act rather than new ones, which is where the arrows across the chart come from.
NOTES_PER_ACT = 40

# Where an edit lands, and how often. These weights are the only lever on the kind mix: material
# added at either end is an add-only hunk, a rewritten passage is a mixed one, a deleted passage
# is a remove-only one. Tuned against `--report`, which measures the corpus this produces with
# the same loader the chart uses and prints it beside the profile it was imitating.
OPS = {"append": 0.26, "prepend": 0.10, "revise": 0.56, "prune": 0.08}

# What share of notes already existed before the window opened. Most of a real vault does — a
# four-week diff of a years-old vault is mostly changes to notes that were already there — and
# without this every note's first appearance is a whole-file creation, which is an add-only hunk
# by definition. Sixty per cent of them starting with a body is what moves the corpus's kind mix
# off "everything is an addition" and onto the profile's.
PRE_HISTORY = 0.85
# Two splices in one week make one net diff with two `@@` blocks — which is where a
# hunks-per-note above 1 comes from, since the reader diffs a note's week as a whole.
TWO_OP_RATE = 0.28

# How much of a note the writer is shown when adding to it. Enough to continue it in the same
# voice and not repeat itself; a long note in full would crowd out the beat it is being asked for.
EXISTING_CHARS = 1500

# Any heading, for the hunk header's git-style section hint. A `##` inside a note is content.
HEADING = re.compile(r"^#{1,6}\s")
# The note's own title, and only that. Stripping every heading level instead is what emptied
# fifty-two passages that legitimately opened with a `## week of …` and turned their note-weeks
# into silent no-ops — the note stopped changing, so the reader stopped listing it.
TITLE = re.compile(r"^#\s")


def paragraphs(text: str) -> list[str]:
    """A note as blocks. A bullet list is one block, which is what makes a splice look human."""
    return [b for b in re.split(r"\n\s*\n", text.strip()) if b.strip()]


def splice(text: str, op: str, passage: str, rng: random.Random) -> str:
    """Put `passage` where `op` says, and return the note as it now stands."""
    blocks = paragraphs(text)
    if not blocks:
        return passage.strip()
    # A note that opens with a heading keeps it. Prepending above the title would be the one
    # thing no editor does.
    head = 1 if TITLE.match(blocks[0]) and len(blocks[0].splitlines()) == 1 else 0
    body = list(range(head, len(blocks)))
    if op == "prune":
        # No passage, and nothing to strip off one. Guarding this with the title rule below is
        # how a prune quietly became a no-op and the corpus lost every removal it had.
        if len(body) > 1:
            del blocks[rng.choice(body)]
        return "\n\n".join(blocks)
    if head:
        # Asked for a passage of a named note, the model writes the note's title again at the
        # top of it, every time. Told not to, it does it anyway about a third of the time — so
        # the title is taken off here instead, where it is not a matter of persuasion. Without
        # this a four-week note ends up with its own H1 stacked four deep, which is the first
        # thing anybody would notice in a diff.
        lines = passage.lstrip().splitlines()
        if lines and TITLE.match(lines[0]):
            passage = "\n".join(lines[1:]).lstrip()
    passage = passage.strip()
    if not passage:
        return text
    if op == "prepend":
        blocks.insert(head, passage)
    elif op == "revise" and body:
        blocks[rng.choice(body)] = passage
    else:
        blocks.append(passage)
    return "\n\n".join(blocks)


def choose_ops(text: str, rng: random.Random) -> list[str]:
    """Which splices this week's edit is made of. Empty note, one op: writing it."""
    if not text.strip():
        return ["create"]
    blocks = paragraphs(text)
    # The body is everything under the title, which is what an edit can actually touch — the
    # same count `splice` works from, so the two cannot disagree about what is possible.
    body = len(blocks) - (1 if TITLE.match(blocks[0]) and len(blocks[0].splitlines()) == 1 else 0)
    names, weights = zip(*OPS.items())
    if body < 1:
        # Nothing to revise around and nothing to spare; a short note grows before it changes.
        names, weights = ("append", "prepend"), (0.75, 0.25)
    elif body < 2:
        # One paragraph: it can be rewritten, but deleting it would empty the note.
        names, weights = ("append", "prepend", "revise"), (0.4, 0.16, 0.44)
    ops = [rng.choices(names, weights)[0]]
    if rng.random() < TWO_OP_RATE and body >= 2:
        second = rng.choices(names, weights)[0]
        if second != ops[0]:
            ops.append(second)
    return ops


INSTRUCTION = {
    "create": "This is the note's first day. Write what goes in it — a title line starting with "
              "a single # if the note would have one, then the opening content. A note starts "
              "small.",
    "append": "Add a new passage at the end of the note, continuing from what is already there. "
              "Do not repeat or restate anything above, and do not write the note's title again "
              "— it already has one.",
    "prepend": "Add a new passage at the top of the note, under its title if it has one. This is "
               "what a dated log does — the newest entry goes first. Give it its own date or day "
               "heading if the note is organised that way, but never the note's own title again "
               "— it already has one.",
    "revise": "Rewrite one passage of this note as it now stands. Keep what it was about and "
              "change what it says: a plan that changed, a figure that was wrong, a decision "
              "that got made. Return only the rewritten passage.",
    # Never emitted as an edit. This is what was already in the note when the window opened, so
    # the note's first real edit is a change to something rather than the creation of everything.
    "history": "This note already existed before any of this. Write what was in it beforehand — "
               "the background the later entries build on, ending mid-thread rather than at a "
               "conclusion. A title line starting with a single # if the note would have one. "
               "Write it as three or four separate passages with a blank line between them, "
               "added on different days and not continuous with each other. Exactly one title "
               "line, at the very top: the passages after it carry no title of their own.",
}

# A model told "one to four short paragraphs" writes four every time, and the corpus came out
# with a median edit four times the size of a real one. So the length is drawn per edit from the
# distribution `synth_profile.py` measured, and asked for in characters. Sampled rather than
# fixed, because the shape is most of the realism: a real week is a pile of one-line edits with
# two or three long evenings in it, and a corpus of uniformly medium paragraphs is neither.
LENGTH = ((0.0, "min"), (0.25, "p25"), (0.5, "median"), (0.75, "p75"), (0.9, "p90"), (1.0, "max"))

# The profile's size distribution is measured over hunks that HAVE a diff — the reader returns a
# short note whole instead, and those never reach it. The sampler cannot know in advance which
# edits will end up rendered whole, so it draws from the full distribution and every short draw
# is then removed from the measurement by exactly that rule, which drags the surviving median up.
# This is the correction, and its value is a measurement: it is what makes `--report`'s median
# land on the profile's rather than at twice it.
LENGTH_SCALE = 0.6

# The smallest budget worth asking for. The real distribution goes well below this — a quarter of
# edits are under ninety characters — but a model told to write forty characters answers with the
# note's title and nothing else, forty-three times out of a hundred and eighty-two. Asked for
# ninety it writes a line. Below the floor the honest thing is not a shorter passage, it is fewer
# of them, and `full_threshold` already turns the short notes into whole-content squares.
MIN_CHARS = 90


def body_of(passage: str) -> str:
    """What a passage says once its title line is discounted. Empty means it said nothing."""
    return "\n".join(l for l in passage.splitlines() if not TITLE.match(l.lstrip())).strip()


def trim(text: str, target: int) -> str:
    """Cut a passage to about `target` characters, at the last boundary that fits.

    Enforced here rather than asked for. The instruction names a length and Haiku writes what it
    was going to write anyway — the corpus came back with a median edit five times the size of a
    real one, and asking more firmly moved it by nothing. So the ask stays (it biases the shape)
    and the number is made true here, where it can be. Cutting mid-thread is not a compromise: a
    notebook is full of entries that stop because the person stopped.

    Applied after the cached call, so retuning the distribution costs nothing.
    """
    text = text.strip()
    room = int(target * 1.35)
    if len(text) <= room:
        return text
    breaks = (("\n\n", 0), ("\n", 0), (". ", 1))
    for sep, keep in breaks:
        cut = text.rfind(sep, 0, room)
        if cut > target * 0.4:
            return text[:cut + keep].rstrip()
    # Nothing inside the budget. Overrun to the next boundary rather than cut mid-clause: a
    # notebook entry stops because the person stopped, and people stop between sentences.
    for sep, keep in breaks:
        cut = text.find(sep, room)
        if cut != -1:
            return text[:cut + keep].rstrip()
    return text


def sample_chars(chars: dict, rng: random.Random, cap: int = 2500,
                 scale: float = LENGTH_SCALE) -> int:
    """One edit's size, drawn from the real distribution by interpolating its own quantiles."""
    u = rng.random()
    for (lo, a), (hi, b) in zip(LENGTH, LENGTH[1:]):
        if u <= hi:
            t = (u - lo) / (hi - lo) if hi > lo else 0
            return int(max(MIN_CHARS, min(cap, scale * (chars[a] + t * (chars[b] - chars[a])))))
    return int(min(cap, scale * chars["max"]))


def head_and_tail(text: str, limit: int = EXISTING_CHARS) -> str:
    """A long note as its opening and its most recent end, which is what a writer would re-read."""
    text = text.strip()
    if len(text) <= limit:
        return text or "(the note does not exist yet)"
    half = limit // 2
    return f"{text[:half].rstrip()}\n\n[…]\n\n{text[-half:].lstrip()}"


def unified(before: str, after: str, stamp_before: str, stamp_after: str) -> str:
    """A real unified diff, headed the way the reader heads one, with git's function context.

    `difflib` writes correct `@@` line counts, which is the whole reason a model is never asked
    for a diff here: those counts are what `_hunks.py` walks to give every square its id.
    """
    old, new = before.splitlines(), after.splitlines()
    body = list(difflib.unified_diff(old, new, n=3, lineterm=""))[2:]
    out = [f"--- {stamp_before}", f"+++ {stamp_after}"]
    for line in body:
        if line.startswith("@@"):
            # git names the enclosing section after the second `@@`; the reader's output carries
            # it, and a hunk header without one reads as machine-made.
            start = int(re.search(r"-(\d+)", line).group(1))
            hint = next((l for l in reversed(old[:max(0, start - 1)]) if HEADING.match(l)), "")
            line = f"{line} {hint}".rstrip()
        out.append(line)
    return "\n".join(out)


# ── generation ───────────────────────────────────────────────────────────────────────────────

def cached(payload: dict, produce, no_cache: bool = False):
    """One call, one file, keyed by everything that decides its answer.

    Per call rather than per pass, which is the same shape `_speech.py` caches a synthesised
    chunk in and is here for the same reason: this is two hundred and fifty calls, and losing
    all of them because the two hundredth failed is not a thing to find out twice. A rerun after
    any failure resumes at the first call that never completed.
    """
    key = cache_path(CACHE_DIR, payload, ".json")
    if key.exists() and not no_cache:
        return json.loads(key.read_text()), True
    value = produce()
    # A failure is not an answer, so it is not written down. `produce` returns None when every
    # draft came back unusable, and caching that would make the next run fail without calling
    # anything — which is exactly what it did the first time this was written.
    if value is not None:
        write_atomic(key, json.dumps(value, ensure_ascii=False).encode())
    return value, False


def roster_targets(profile: dict) -> dict:
    """How big a cast a month of these habits implies.

    Mentions divided by how often a name recurs. A notebook that names two people an edit over
    two hundred edits is not a notebook with four hundred people in it — it is one with thirty,
    each turning up a dozen times, and the recurrence is the part worth reproducing.
    """
    per = (profile.get("entities") or {}).get("per_hunk", {})
    hunks = profile["hunks_per_week"]["median"] * WEEKS

    def size(name: str, recur: float, floor: int, cap: int) -> int:
        return int(max(floor, min(cap, round(per.get(name, 0.5) * hunks / recur))))

    return {"people": size("people", 9, 14, 34), "places": size("places", 4, 8, 20),
            "organizations": size("organizations", 6, 10, 24),
            "products": size("numbers", 12, 8, 20), "events": size("events", 3, 5, 12)}


def generate(profile: dict, style: str, dates: list[str], seed: int,
             verbose: bool, no_cache: bool, jobs: int, story=None) -> dict:
    """Every model call this feature makes, in order. Each one cached on its own.

    Nothing here is filtered. The wall that keeps the real vault out of these calls is
    `synth_profile.py`'s return type, and it is upstream of this function; a word list here
    would add nothing to it and did in practice subtract the only thing a journal is for.
    """
    os.environ["ANTHROPIC_API_KEY"] = api_key("ANTHROPIC_API_KEY")
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    try:
        from baml_sdk import MakeActNotes, MakeRoster, MakeThreads, WriteContext, WriteEdit
    except ImportError as exc:  # pragma: no cover - a setup failure, not a runtime one
        sys.exit(f"Could not import the generated BAML client ({exc}).\nRun: just baml")

    rng = random.Random(seed)
    # The story's own subjects when there is one — a month with a death and a lawsuit in it does
    # not divide into cooking and cycling — and the generic set otherwise.
    subjects = list(story.SUBJECTS) if story is not None else list(SUBJECTS)
    topics = "\n".join(f"- {t}" for t in subjects)
    base = {"prompt": PROMPT.read_text(errors="replace") if PROMPT.is_file() else "",
            "style": style}
    dropped = {"beats": 0, "passages": 0, "no-ops": 0}

    # ── 1. the cast ──────────────────────────────────────────────────────────────────────
    targets = roster_targets(profile)
    counts = "\n".join(f"- {k}: {v}" for k, v in targets.items())

    def make_roster() -> dict:
        r = MakeRoster(counts=counts, topics=topics, style=style)
        return {k: list(getattr(r, k)) for k in
                ("people", "places", "organizations", "products", "events")}

    if story is not None:
        # A story brings its own cast, and it has to be exactly that cast — the names are the
        # one thing a reader could check the answer against, so they are not left to a model.
        roster, hit = story.roster(), True
    else:
        roster, hit = cached({**base, "fn": "MakeRoster", "counts": counts, "topics": topics},
                             make_roster, no_cache)
    roster_text = "\n".join(f"- {k}: {', '.join(v)}" for k, v in roster.items())
    print(f"roster   {sum(len(v) for v in roster.values())} names"
          + (f" from {story.NAME}" if story is not None else " (cached)" if hit else ""))

    # ── 2. the week's own sources, so the notes can cite them ────────────────────────────
    digests = {}
    for date in dates:
        digests[date] = (f"{digest_oura(oura(date, seed))} "
                         f"{digest_finances(finances(date, seed, roster['organizations'] + roster['places']))}")
    weeks_text = "\n".join(
        f"- Week {i + 1}, ending {date}. {digests[date]}" for i, date in enumerate(dates))

    # ── 3. the notes, and what happens in each of them week by week ──────────────────────
    def plan_topic(topic: str) -> tuple[list, bool]:
        wanted = (
            f'Plan {NOTES_PER_TOPIC} notes on the subject "{topic}" and nothing else. Between '
            f"them they should hold about {NOTES_PER_TOPIC * 3} beats across the {len(dates)} "
            f"weeks. At least one of the {NOTES_PER_TOPIC} must have a beat in three or four "
            f"different weeks, and what happens in its later beats must follow from its earlier "
            f'ones. Give every beat the topic "{topic}" exactly.'
        )
        if topic == subjects[0]:
            wanted += (" One of these notes is the running journal, named for the year, with a "
                       "beat in every single week — day-by-day entries about whatever happened, "
                       "including the people and the other notes' subjects.")

        def produce() -> list:
            found = MakeThreads(topics=f"- {topic}", roster=roster_text, weeks=weeks_text,
                                style=style, wanted=wanted)
            return [{"note": t.note, "topic": topic,
                     "beats": [{"week": int(b.week), "summary": b.summary} for b in t.beats]}
                    for t in found]

        return cached({**base, "fn": "MakeThreads", "topic": topic, "wanted": wanted,
                       "roster": roster_text, "weeks": weeks_text}, produce, no_cache)

    # Sixteen calls that know nothing about each other, so they go at once. `map` hands the
    # results back in the order they were asked for, which is what keeps a run reproducible:
    # the note list must not depend on which topic the network happened to answer first.
    threads = []
    if story is not None:
        # One call per act, in order, each shown what the earlier acts left behind. Sequential on
        # purpose and for the same reason `unit_topics.py` is: the list of files this person keeps
        # is built by writing, and an act that can see the earlier files can carry one forward
        # instead of opening a new one. Carrying forward is what puts an arrow across the chart.
        for i, date in enumerate(dates):
            so_far = "\n".join(f"- {t['note']} ({t['topic']})" for t in threads) \
                or "(nothing yet — this is the first week, every file starts here)"
            wanted = (
                f"Plan about {NOTES_PER_ACT} notes for this week. At least half must be files "
                f"carried forward from the list above, named exactly as they appear there; the "
                f"rest are new files this week made necessary. Give each note ONE beat: what goes "
                f"into it this week.\n\n"
                f"Two of them are not optional and are the same two every week: the running "
                f"journal named for the year, and the writer's own log of what they did and how "
                f"they were. Their beats this week come from the feeling-thinking-doing section "
                f"above, in the writer's own words and in detail — those two files are where the "
                f"week is actually recorded, and the rest of the notes are what the week made "
                f"them deal with."
            )
            act = story.synopsis(i)
            week = f"Week {i + 1} of 4, ending {date}. {digests[date]}"

            def produce(act=act, so_far=so_far, week=week, wanted=wanted) -> list:
                found = MakeActNotes(act=act, so_far=so_far, roster=roster_text, week=week,
                                     topics=topics, style=style, wanted=wanted)
                return [{"note": t.note, "topic": t.topic,
                         "beats": [{"summary": b.summary} for b in t.beats]} for t in found]

            found, hit = cached({**base, "fn": "MakeActNotes", "act": act, "so_far": so_far,
                                 "week": week, "wanted": wanted, "roster": roster_text},
                                produce, no_cache)
            kept = 0
            for t in found:
                note = re.sub(r"[^a-zA-Z0-9._-]", "-", t["note"].strip()) or "note.md"
                note = note if note.endswith(".md") else note + ".md"
                # The week is this act's, not whatever the model put in the field. It was asked
                # for one week and an id that disagreed with the folder it is in would be a
                # square in the wrong column.
                beats = [{"week": i + 1, "summary": b["summary"]} for b in t["beats"]]
                if beats:
                    threads.append({"note": note, "topic": t["topic"], "beats": beats[:1]})
                    kept += 1
            carried = sum(1 for t in threads[-kept:] if
                          sum(1 for u in threads[:-kept] if u["note"] == t["note"]))
            print(f"act {story.ACTS[i]['act']:<3} {date}  {kept} notes, {carried} carried forward"
                  + (" (cached)" if hit else ""))
        planned = []
    else:
        with ThreadPoolExecutor(max_workers=jobs) as pool:
            planned = list(pool.map(plan_topic, subjects))
    for topic, (found, hit) in zip(subjects, planned):
        kept = 0
        for t in found:
            note = re.sub(r"[^a-zA-Z0-9._-]", "-", t["note"].strip()) or "note.md"
            note = note if note.endswith(".md") else note + ".md"
            beats = [{"week": max(1, min(len(dates), b["week"])), "summary": b["summary"]}
                     for b in t["beats"]]
            if beats:
                threads.append({"note": note, "topic": topic, "beats": beats})
                kept += 1
        print(f"threads  {topic:<18} {kept} notes, "
              f"{sum(len(t['beats']) for t in threads if t['topic'] == topic)} beats"
              f"{' (cached)' if hit else ''}")

    # One filename is one file. Two threads naming it are the same note returned to, which is
    # the most valuable thing on this chart — an earlier version of it used to rename the second
    # one and quietly destroy exactly the structure the story mode exists to create. The topic
    # comes from the first mention, so a note keeps one colour for its whole life.
    merged: dict[str, dict] = {}
    for t in threads:
        m = merged.setdefault(t["note"], {"note": t["note"], "topic": t["topic"], "beats": []})
        m["beats"] += t["beats"]
    threads = list(merged.values())

    # ── 4. the edits ─────────────────────────────────────────────────────────────────────
    schedule: dict[str, list] = {}
    for w in range(1, len(dates) + 1):
        for t in threads:
            for beat in t["beats"]:
                if beat["week"] == w:
                    # A note changes once a week; the reader diffs a note's whole week as one net
                    # change, so a second beat in the same week is not a second hunk.
                    schedule.setdefault(t["note"], []).append((w, t, beat))
                    break
    total = sum(len(v) for v in schedule.values())
    print(f"edits    {total} note-weeks across {len(schedule)} notes")

    done, hits = [0], [0]

    def write_note(item: tuple[str, list]) -> list[dict]:
        """One note's whole life, in order. Notes do not know about each other, so they run at once.

        The random stream is seeded from the note's own name rather than shared, which is what
        makes the result identical however the pool happens to schedule them — without that, a
        parallel run and a sequential one would splice the same passage in different places.
        """
        note, items = item
        rng = random.Random(f"{seed}-{note}")

        def ask(op: str, existing: str, context: str, target: int) -> str | None:
            """One passage, cached and cut to size. None if two drafts both came back empty."""
            size = (f" Write about {target} characters — that is the size of this edit, and it "
                    f"matters more than finishing a thought. "
                    + ("A line or two." if target < 160 else
                       "A short paragraph or a few list items." if target < 500 else
                       "Several paragraphs; this was a long sitting."))

            def produce() -> str | None:
                # One retry, and the second ask says what went wrong. A draft that comes back as
                # nothing but the note's own title splices to nothing, and a note-week that
                # changes nothing is a square that never appears on the chart.
                for attempt in range(2):
                    extra = ("" if attempt == 0 else
                             " Your previous attempt returned nothing but the note's own "
                             "heading. Write the body of the entry itself.")
                    passage = WriteEdit(
                        note=note, topic=topic, beat=context,
                        instruction=INSTRUCTION[op] + size + extra, existing=existing,
                        roster=roster_text, style=style).text
                    if body_of(passage):
                        return passage
                return None

            passage, hit = cached(
                {**base, "fn": "WriteEdit", "note": note, "topic": topic, "beat": context,
                 "op": op, "existing": existing, "roster": roster_text, "target": target},
                produce, no_cache)
            hits[0] += hit
            if passage is None or not body_of(passage):
                dropped["passages"] += 1
                return None
            # The length is made true here rather than in the prompt — see trim(). After the
            # cache, so retuning the distribution costs nothing.
            return trim(passage, target)

        topic = items[0][1]["topic"]
        state, out = "", []

        # What was in the note before the window opened, for most notes. Never emitted: it is
        # the context lines the first real edit is a change against.
        if rng.random() < PRE_HISTORY:
            target = int(2.5 * sample_chars(profile["hunk_chars"], rng))
            passage = ask("history", "(the note does not exist yet)",
                          f"{items[0][2]['summary']}\n\nThis is background, written earlier.",
                          target)
            state = passage or ""

        for w, t, beat in items:
            before, after = state, state
            context = (f"{beat['summary']}\n\nThe week ending {dates[w - 1]}. "
                       f"{digests[dates[w - 1]]}")
            ops = choose_ops(before, rng)
            for op in ops:
                if op == "prune":
                    after = splice(after, op, "", rng)
                    continue
                # Split across the splices, so two of them in one week still add up to one
                # week-sized edit rather than to two.
                target = max(MIN_CHARS, sample_chars(profile["hunk_chars"], rng) // len(ops))
                passage = ask(op, head_and_tail(after), context, target)
                if passage is not None:
                    after = splice(after, op, passage, rng)
            if after == before:
                # A splice that landed on nothing: a prune with nothing spare to prune, or a
                # passage that was only the title. The reader lists notes that changed, so this
                # note-week is not a square — but it is worth counting, because a lot of them
                # means the op weights are asking for edits the notes cannot absorb.
                dropped["no-ops"] += 1
            state = after
            out.append({"week": w, "note": note, "topic": t["topic"],
                        "before": before, "after": after})
            done[0] += 1
            if verbose:
                print(f"  {done[0]:>4}/{total}  {note}")
            elif done[0] % 20 == 0 or done[0] == total:
                print(f"  {done[0]:>4}/{total}")
        return out

    with ThreadPoolExecutor(max_workers=jobs) as pool:
        written = list(pool.map(write_note, schedule.items()))
    # Back into one list in a fixed order, so the corpus does not depend on the pool.
    edits = sorted((e for chain in written for e in chain), key=lambda e: (e["week"], e["note"]))

    # ── 5. the four openers the writer fills in before the week is read ──────────────────
    #
    # `prompts/act-analysis.md` hands a person four half-sentences to finish — "This upcoming
    # week...", "Tomorrow...", "Today...", "Emotionally, I..." — and the synthetic run answers
    # them here, in the writer's own first person, so the bundle carries them finished. They are
    # the only part of the corpus addressed to the letter's reader rather than to the writer, and
    # the only place the week says what it was *like* rather than what happened, so they are
    # written from the act's interior material and not merely from the week's beats.
    by_note = {t["note"]: t for t in threads}
    contexts = {}
    for w, date in enumerate(dates, 1):
        beats = "\n".join(
            f"- {e['note']}: {b['summary']}"
            for e in edits if e["week"] == w
            for b in by_note[e["note"]]["beats"] if b["week"] == w) or "(a quiet week)"
        act = (story.synopsis(w - 1) if story is not None else
               "(no story — write from the week's notes below, and nothing else)")

        last = [""]

        def write_context(date=date, beats=beats, act=act, last=last) -> str | None:
            # The labels are checked rather than trusted. A draft that drops one leaves a blank
            # in the bundle where the read expects an answer, and the read is the whole product.
            for _ in range(2):
                text = WriteContext(week=date, act=act, beats=beats, roster=roster_text,
                                    style=style).text
                last[0] = text
                if has_openers(text):
                    return text
            return None

        text, hit = cached({**base, "fn": "WriteContext", "week": date, "beats": beats,
                            "act": act, "roster": roster_text}, write_context, no_cache)
        if text is None:
            sys.exit(f"Could not get the four openers back for {date} in two attempts.\n"
                     "  Every draft dropped one of `This upcoming week`, `Tomorrow`, `Today`,\n"
                     "  `Emotionally, I`, or returned them out of order.\n"
                     "  Rerun with --no-cache for a different draft.\n\n"
                     "  The last draft began:\n"
                     + "\n".join(f"    {line}" for line in last[0][:600].splitlines()))
        contexts[date] = text
        print(f"context  {date}{' (cached)' if hit else ''}")

    if any(dropped.values()):
        print(f"\ndropped  {dropped['beats']} beats, {dropped['passages']} empty passages; "
              f"{dropped['no-ops']} note-weeks that changed nothing")
    print(f"cache    {hits[0]} passages were already on disk")
    return {"roster": roster, "threads": threads, "edits": edits, "contexts": contexts}


# ── assembly ─────────────────────────────────────────────────────────────────────────────────

def full_threshold(edits: list[dict], rate: float) -> int:
    """Below how many characters a note comes back whole instead of as a diff.

    The reader's own rule is a length threshold, and the profile says what fraction of squares it
    catches. Solving for the threshold rather than fixing it keeps that fraction right whatever
    length the generated notes happen to run to.
    """
    lengths = sorted(len(e["after"]) for e in edits)
    if not lengths:
        return 600
    return int(max(220, min(1400, lengths[min(len(lengths) - 1, int(rate * len(lengths)))])))


def microlite_md(date: str, week_edits: list[dict], threshold: int, vault: int,
                 rng: random.Random, held: str = "", after: str = "") -> str:
    """One week of edits as the reader would have written them out.

    Dates are printed without their year, the way the folder is named, because this file is read
    by `_hunks.py` and its `_generated` line is the fallback the week key comes from — so the two
    must agree — and because these are the dates a reader sees beside every diff.

    `date` is the Friday the week's edits are counted to, and what every draw below is measured
    from, so moving the read does not reshuffle the week. `held` is the day the read happened
    when that is later (see `_synth.HELD`); the header carries it. `after` is the day of the read
    before, and no edit lands on or before it, since whatever was written by then was in that one.
    """
    end = dt.date.fromisoformat(date)
    start = end - dt.timedelta(days=6)
    read = dt.date.fromisoformat(held or date)
    floor = dt.date.fromisoformat(after) if after else None
    day_of = lambda d: f"{d:%m-%d}"   # noqa: E731 — one expression, used five times below

    # Each note-week gets a day and an hour, so the activity table is read off the same facts
    # the diffs are. Late evenings are over-represented, because that is when a notebook is used.
    when = {}
    for e in week_edits:
        day = start + dt.timedelta(days=rng.randint(0, 6))
        if floor and day <= floor:
            day = floor + dt.timedelta(days=1)
        hour = rng.choices(range(6, 24), [1, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 3, 4, 5, 6, 6, 4, 2])[0]
        when[e["note"]] = (day, hour)

    by_day: dict[dt.date, dict] = {}
    for e in week_edits:
        day, hour = when[e["note"]]
        d = by_day.setdefault(day, {"notes": 0, "edits": 0, "add": 0, "dele": 0, "hours": set()})
        was, now = set(e["before"].splitlines()), set(e["after"].splitlines())
        added = sum(len(l) for l in e["after"].splitlines() if l not in was)
        removed = sum(len(l) for l in e["before"].splitlines() if l not in now)
        d["notes"] += 1
        d["edits"] += max(1, round((added + removed) / 160))
        d["add"] += added
        d["dele"] += removed
        d["hours"].add(hour)

    rows = []
    for day in sorted(by_day):
        d = by_day[day]
        hrs = sorted(d["hours"])
        span = f"{hrs[0]:02d}:00–{hrs[-1]:02d}:59"
        late = "⚠️" if hrs[-1] >= 23 else ""
        rows.append(f"| {day_of(day)} | {d['notes']} | {d['edits']} | {d['add']} | "
                    f"{d['dele']} | {span} | {late} |")

    sections = []
    for e in sorted(week_edits, key=lambda e: when[e["note"]], reverse=True):
        if e["after"] == e["before"]:
            continue
        day, hour = when[e["note"]]
        n_edits = max(1, min(30, round(abs(len(e["after"]) - len(e["before"])) / 90)
                             + rng.randint(0, 3)))
        head = f"## {e['note']} — {n_edits} edit{'s' if n_edits != 1 else ''} in window"
        if len(e["after"]) < threshold:
            # Short enough that the reader hands the note back whole rather than as a diff.
            sections.append(f"{head}\n\n_current content:_\n\n```markdown\n{e['after']}\n```")
            continue
        stamp_b = f"{(start - dt.timedelta(days=rng.randint(1, 20))):%m-%d} " \
                  f"{rng.randint(6, 22):02d}:{rng.randint(0, 59):02d}:{rng.randint(0, 59):02d}"
        stamp_a = f"{day:%m-%d} {hour:02d}:{rng.randint(0, 59):02d}:{rng.randint(0, 59):02d}"
        sections.append(f"{head}\n\n```diff\n"
                        f"{unified(e['before'], e['after'], stamp_b, stamp_a)}\n```")

    snapshots = sum(d["edits"] for d in by_day.values()) * rng.randint(6, 11)
    return (
        f"# Hunking Obsidian\n\n"
        f"_generated {read:%a} {day_of(read)} 10:15:04 · {snapshots} snapshots across {vault} notes_\n\n"
        f"## Activity by day\n\n"
        f"_(live edits only; bulk syncs excluded — see below)_\n\n"
        f"| Date | Notes | Edits | +chars | −chars | Active hrs | Late-night |\n"
        f"|------|------:|------:|-------:|-------:|------------|:----------:|\n"
        + "\n".join(rows) + "\n\n\n" + "\n\n\n".join(sections) + "\n"
    )


FRONT_MATTER = """---
title: ACT re-entry read — synthetic week
slug: compaction
date: {date}
interlocutor: Bobby
since: 7
diff: {diff}
attachments: {attachments}
calendar:
music:
music-engine:
engine:
voice: WeAAwKYcS06VmXw086yZ
voice-sample:
llm: claude
model: opus
effort:
---

<!-- Written by tools/synth_corpus.py. Every name, note and figure below is invented; see
     synthetic/README.md. The pipeline reads this file exactly as it reads a real week's. -->

{context}
"""


def write_week(date: str, week_edits: list[dict], sources: dict, threshold: int,
               vault: int, seed: int, context: str, root: Path,
               held: str = "", after: str = "") -> Path:
    """One session directory: the diff, the two sources, and the file the run is started from.

    Named `mm-dd`, without the year — see `_synth.label` — after the day the read happened,
    which is `held` when that is not the week's Friday. The two source files take the same
    name, and those two are the only filenames from this folder a reader ever sees: the
    connectome draws a square for each of them and labels it with the filename. What is in them
    stays counted to the Friday, so the figures the notes quote are still the ones they carry.
    """
    stem = label(held or date)
    session = root / stem
    session.mkdir(parents=True, exist_ok=True)
    rng = random.Random(f"layout-{date}-{seed}")

    (session / "microlite.md").write_text(
        microlite_md(date, week_edits, threshold, vault, rng, held, after))
    oura_path = session / f"oura-{stem}.md"
    fin_path = session / f"finances-{stem}.md"
    oura_path.write_text(oura_md(sources["oura"]))
    fin_path.write_text(finances_md(sources["finances"]))
    (session / "edit-me.md").write_text(FRONT_MATTER.format(
        date=stem, diff=session.resolve() / "microlite.md",
        attachments=f"{fin_path.resolve()}, {oura_path.resolve()}",
        context=context.strip()))
    # The empty place the letter goes, exactly as `--new` would leave it, so `just synth-letters`
    # has something to overwrite and `just render` refuses until it has been.
    ensure_stub(session)
    return session


def report(root: Path, profile: dict) -> None:
    """Measure what was written with the loader the chart uses, beside what it was imitating."""
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from _hunks import load
    weeks = load(sorted(root.glob("*/microlite.md")))
    hunks = [h for w in weeks for h in w["hunks"]]
    if not hunks:
        return
    kinds = {k: sum(1 for h in hunks if h["kind"] == k) / len(hunks)
             for k in ("added", "mixed", "removed", "full")}
    diffs = [h for h in hunks if h["kind"] != "full"] or hunks
    med = sorted(h["chars"] for h in diffs)[len(diffs) // 2]
    print("\n            synthetic   real")
    print(f"  hunks/wk   {len(hunks) / len(weeks):>8.0f}   {profile['hunks_per_week']['median']:.0f}")
    print(f"  notes/wk   {sum(len(w['notes']) for w in weeks) / len(weeks):>8.0f}   "
          f"{profile['notes_per_week']['median']:.0f}")
    for k in ("added", "mixed", "removed", "full"):
        print(f"  {k:<9}  {kinds[k]:>8.0%}   {profile['kind_mix'][k]:.0%}")
    print(f"  chars med  {med:>8.0f}   {profile['hunk_chars']['median']:.0f}")


def assemble(plan: dict, dates: list[str], profile: dict, seed: int, out: Path,
             keep_letters: bool = True, threshold: int | None = None,
             keys: dict[str, str] | None = None,
             held: dict[str, str] | None = None) -> tuple[list[Path], int]:
    """The plan on disk: four session directories.

    Separate from `main` because `synth_links.py` writes the same vault from a plan it has added
    to, and two implementations of "what a session directory is" is the one thing this feature
    cannot afford — a note's content and its position in a file are what every id on the
    connectome resolves through.

    `keep_letters` is what makes it re-runnable. A fresh corpus replaces the vault whole, because
    half of one run and half of another share note titles without sharing their contents; a
    re-assembly after planting links must not throw away the letters that were written from it.
    """
    payees = plan["roster"]["organizations"] + plan["roster"]["places"]
    # Passed in by a caller that has changed the plan since. The threshold is a quantile over
    # every note's length, so adding a few lines to week four moves it, and a moved threshold
    # re-renders notes in EVERY week — flipping some between a diff and whole content, which
    # renumbers hunks the chart has already drawn arrows to. A caller planting into one week
    # holds the original so the other three come out byte-identical.
    if threshold is None:
        threshold = full_threshold(plan["edits"], profile["kind_mix"]["full"])
    # The reader's header counts the whole vault, not the week — a note nobody touched this week
    # is still a note in the folder it read.
    vault = len({e["note"] for e in plan["edits"]})

    # What the sleep report and the ledger are drawn from, when that is not the date they are
    # labelled with. `synth_vault` passes the reference calendar its notes were written against,
    # so the figures those notes quote stay true however far the corpus is shifted.
    keys = keys or {}
    saved = {}
    if out.exists():
        if keep_letters:
            saved = {p.parent.name: p.read_text()
                     for p in out.glob("*/lifelog-*.md") if p.is_file()}
        # Only the week directories. The rendered pages sit beside them, at the top of this
        # folder, and taking the whole tree took those with it — so regenerating the corpus
        # silently deleted the charts it exists to feed.
        for week in out.glob("*/"):
            if week.is_dir():
                shutil.rmtree(week)

    # The day each week was actually read, where that is not its Friday — `_synth.HELD`. Each
    # read is also the floor under the next week's edits.
    held = held or {}
    written, after = [], ""
    for date in dates:
        week_edits = [e for e in plan["edits"] if dates[e["week"] - 1] == date]
        key = keys.get(date, date)
        sources = {"oura": oura(date, seed, key), "finances": finances(date, seed, payees, key)}
        read = held.get(date, date)
        session = write_week(date, week_edits, sources, threshold, vault,
                             seed, plan["contexts"][date], out, held=read, after=after)
        after = read
        if (stem := label(read)) in saved:
            (session / f"{LIFELOG}-{stem}.md").write_text(saved[stem])
        written.append(session)

    return written, threshold


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Four weeks of a vault that never existed, in the formats the pipeline reads.")
    ap.add_argument("--end", default=ANCHOR, help=f"Date of the newest week (default {ANCHOR}).")
    ap.add_argument("--weeks", type=int, default=WEEKS, help=f"How many weeks (default {WEEKS}).")
    ap.add_argument("--seed", type=int, default=7, help="Seed for every non-model choice.")
    ap.add_argument("--out", type=Path, default=SESSIONS, help="Where the sessions go.")
    ap.add_argument("--fresh", action="store_true",
                    help="Drop the letters too, back to stubs. Off by default: a letter is four "
                         "Opus calls and twenty minutes, and re-laying-out the notes is neither.")
    ap.add_argument("--no-cache", action="store_true", help="Generate again rather than reuse.")
    ap.add_argument("--dry-run", action="store_true", help="Say what it would cost. No call.")
    ap.add_argument("--story", metavar="NAME",
                    help="Plan each week as one act of a story instead of topic by topic. "
                         "`hamlet` is the one that ships (tools/_story.py). A vault with a plot "
                         "in it is a chart whose connections have a known answer.")
    ap.add_argument("--jobs", type=int, default=8,
                    help="Model calls in flight at once (default 8). Notes are independent of "
                         "each other and each carries its own random stream, so the corpus is "
                         "the same whatever this is set to.")
    ap.add_argument("--verbose", action="store_true", help="Name every note as it is written.")
    args = ap.parse_args()

    story = None
    if args.story:
        import importlib
        try:
            story = importlib.import_module("_story")
        except ImportError as exc:  # pragma: no cover - a setup failure, not a runtime one
            sys.exit(f"No story module ({exc}).")
        if story.NAME != args.story:
            sys.exit(f"--story {args.story}: the module here is {story.NAME}.")

    # Both are written by `just synth-profile` from the real vault, and both are gitignored: they
    # are measurements of a private notebook rather than anything synthetic, so a clone arrives
    # without them and has to measure its own. Named separately because a missing one is a
    # missing input, not a bug to read a traceback about.
    for needed in (PROFILE, STYLE_GUIDE):
        if not needed.is_file():
            sys.exit(f"No {needed.name} at {needed} — run: just synth-profile")
    profile = json.loads(PROFILE.read_text())
    style = STYLE_GUIDE.read_text()
    dates = week_dates(args.end, args.weeks)

    subjects = story.SUBJECTS if story is not None else SUBJECTS
    # The vault this repo actually ships is hand-written now — see tools/synth_vault.py. This
    # still works and is still worth having (it is what measured the shape, and a corpus with no
    # plot in it is the null hypothesis a plotted one has to beat), but running it replaces the
    # assembled sessions. synthetic/vault/ is the source and survives, so the way back is one
    # command; saying so here is cheaper than finding out.
    if (SYNTH_ROOT / "vault").is_dir():
        print("note     synthetic/vault/ exists — this overwrites the sessions assembled from "
              "it.\n         `just synth-vault` puts them back.\n")
    print(f"weeks    {len(dates)}: {', '.join(dates)}")
    print(f"subjects {len(subjects)}"
          + (f", from {story.NAME}" if story is not None else ", the generic set"))

    # Each call is cached on its own under share/.baml-cache, so this is what a cold run costs
    # and a warm one costs nothing. The estimate is the roster, one plan per topic, one context
    # per week, and one passage per note-week — which is what the profile's edit rate implies.
    est = 1 + len(subjects) + len(dates) + int(profile["hunks_per_week"]["median"] * len(dates))
    print(f"calls    up to ~{est}, each cached individually — a rerun pays only for what changed")

    if args.dry_run:
        print("\nDry run — no API call made, nothing billed.")
        return

    print()
    plan = generate(profile, style, dates, args.seed, args.verbose,
                    args.no_cache, args.jobs, story)

    written, threshold = assemble(plan, dates, profile, args.seed, args.out,
                                  keep_letters=not args.fresh)
    print(f"\n{len(written)} sessions · {len(plan['edits'])} note-weeks · "
          f"whole notes under {threshold:,} chars")
    for session in written:
        print(f"  wrote  {link(session)}")
    report(args.out, profile)
    print(f"\nNext:  just synth-letters      (opus writes each week's letter)")


if __name__ == "__main__":
    main()
